### ISSUE TITLE
Unable to format URLs

### ISSUE THREAD

**Issue by clivecrous** [slack-ruby/slack-ruby-client#109]
Any URLs formatted with a label, for example:

`Please visit <http://www.example.com|my website>` do not get formatted correctly as per Slack spec with just text "my website" as a link to http://www.example.com, instead it becomes a literal `&lt;http://www.example.com|my website&gt;` when appearing within Slack.

I'm using slack-ruby-client 0.7.7

**Comment by dblock** [comment]
This is via web and/or real-time API? Post a simple repro?

**Comment by clivecrous** [comment]
```
require 'slack-ruby-client'

Slack.configure do |config|
  config.token = ENV['SLACK_API_TOKEN']
  config.logger = Logger.new(STDOUT)
  config.logger.level = Logger::INFO
  fail 'Missing ENV[SLACK_API_TOKEN]!' unless config.token
end

$slack_client = Slack::RealTime::Client.new

$slack_client.on :hello do
  puts 'Successfully connected.'
end

$slack_client.on :message do |data|

  if data.text.strip.downcase =~ /ping/
    $slack_client.message channel: data.channel, text: "Pong! Brought to you by <http://www.google.com|our sponsors>"
  end

end

$slack_client.start!
```

**Comment by clivecrous** [comment]
How this _should_ behave:

https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22Pong!%20Brought%20to%20you%20by%20%3Chttp%3A%2F%2Fwww.google.com%7Cour%20sponsors%3E%22%7D

**Comment by clivecrous** [comment]
What it's currently (incorrectly) doing:

https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22Pong!%20Brought%20to%20you%20by%20%26lt%3Bhttp%3A%2F%2Fwww.google.com%7Cour%20sponsors%26gt%3B%22%7D

**Comment by dblock** [comment]
This client is certainly not encoding this message AFAIK, but I could be wrong. From here you should be able to debug it. I bet we send the right message but slack encodes it server-side.

**Comment by clivecrous** [comment]
I have been unable to debug or figure out where/why this is happening.

All that I'm aware of is that it's impossible to send through labeled URLs using this client.

**Comment by dblock** [comment]
Worked with web API:

```ruby
require 'slack-ruby-client'

Slack.configure do |config|
  config.token = ENV['SLACK_API_TOKEN']
  fail 'Missing ENV[SLACK_API_TOKEN]!' unless config.token
end

client = Slack::Web::Client.new

client.auth_test

client.chat_postMessage(channel: '#general', text: 'Please visit <http://www.example.com|my website>!', as_user: true)
```

![screen shot 2016-10-17 at 2 39 27 pm](https://cloud.githubusercontent.com/assets/542335/19450464/86ed3242-9477-11e6-943e-be47ab9fed82.png)

In your code you can do:

```ruby
client.web_client.chat_postMessage(channel: data.channel, text: 'Please visit <http://www.example.com|my website>!')
```

Formatting messages in https://api.slack.com/rtm says the following.

![screen shot 2016-10-17 at 2 40 38 pm](https://cloud.githubusercontent.com/assets/542335/19450490/b003d7d0-9477-11e6-9e02-722e2e9a4240.png)

Related, https://github.com/slackhq/python-rtmbot/issues/50 and https://github.com/slackhq/hubot-slack/issues/114 are examples of the same problem and are saying that this isn't supported server-side.

**Comment by clivecrous** [comment]
Fantastic, thank you very much for finding this out and following up.  Sorry for having wasted your time (perhaps it might be worth making a small note about this in your own gem's documentation?)

**Comment by dblock** [comment]
I would appreciate a PR that clarifies the README anywhere you see fit!
