### ISSUE TITLE
Prevent RTM from keeping two connections to the same bot token

### ISSUE THREAD

**Issue by p1Machado** [slack-ruby/slack-ruby-client#111]
I am running a Rails server to handle many bots created by an Slack App. For some reason that I haven't confirmed yet, the rails server is running duplicated, apparently the web server (Pushion Passenger) is trying to start twice.

I know that this is the major problem, but there is some way to prevent RTM from keeping two connections to the same bot token?

**Comment by dblock** [comment]
There's no built-in mechanism to prevent multiple RTM connections from being opened with the same token, you have to build this around in your service.

I'll close this, I don't think the client should be responsible for how it's being managed. It's really just the interface piece that knows nothing about its host.

**Comment by p1Machado** [comment]
Thanks

**Comment by p1Machado** [comment]
I did a getPresence check to avoid starting a second connection. :B

`unless web_client.users_getPresence(user: bot_user_id).presence == 'active'`

**Comment by dblock** [comment]
I guess that works, but it's not transactional. Slack could be down, the other bot may be coming up, etc.
