### ISSUE TITLE
Other RTM events not supported?

### ISSUE THREAD

**Issue by markediez** [slack-ruby/slack-ruby-client#120]
Hi, I'm probably just not doing it right but I can't seem to get any other event working besides :hello, :message, :close, and :closed

Given the starter code, then adding

```
client.on :client_joined do |data|
    puts "Someone joined the channel"
    puts data
end
```

Nothing happens when someone joins the channel.

**Comment by dblock** [comment]
Is it because it's `channel_joined` not `client_joined`?

Example in https://github.com/dblock/slack-amber-alert/blob/e99065878099d05b0da847d125213ff984e00594/slack-amber-alert/server.rb#L12.
