### ISSUE TITLE
Slack::Web::Api::Error not_in_channel error when running the example

### ISSUE THREAD

**Issue by DannyBen** [slack-ruby/slack-ruby-client#124]
- Registered a new bot on Slack, got the token
- Copied the [hi_web example][1] code, used my token
- When running, getting `not_in_channel` error
- (I know authentication is working, since changing the token returned a different error: `invalid_auth`)

```
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/slack-ruby-client-0.7.7/lib/slack/web/faraday/response/raise_error.rb:9:in `on_complete': not_in_channel (Slack::Web::Api::Error)
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/response.rb:9:in `block in call'
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/response.rb:61:in `on_complete'
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/response.rb:8:in `call'
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/request/url_encoded.rb:15:in `call'
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/request/multipart.rb:14:in `call'
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/connection.rb:377:in `run_request'
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/connection.rb:177:in `post'
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/slack-ruby-client-0.7.7/lib/slack/web/faraday/request.rb:25:in `request'
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/slack-ruby-client-0.7.7/lib/slack/web/faraday/request.rb:10:in `post'
        from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/slack-ruby-client-0.7.7/lib/slack/web/api/endpoints/chat.rb:77:in `chat_postMessage'
        from test.rb:9:in `<main>'
```

[1]: https://github.com/slack-ruby/slack-ruby-client/blob/master/examples/hi_web/hi.rb

**Comment by dblock** [comment]
That error seems to be saying that you're posting to a channel that you're not a member of. Does inviting the bot user to the channel help?

**Comment by DannyBen** [comment]
Didnt try. I need to be able to post to channels without being invited to them.

When this failed, I actually went ahead and simply tested the direct HTTP API, with something like this, and it worked:

```ruby
def post(text)
  channel  = 'general'
  username = 'bot'
  text = URI.encode text
  url = "https://slack.com/api/chat.postMessage?token=#{token}&channel=#{channel}&text=#{text}&pretty=1&username=#{username}"
  uri = URI url
  Net::HTTP.get uri
end
```

Another "by the way" - I thought maybe the channel name was the problem, so tried `#general`, `general` and the `Cnnnnnnnn` code of the channel. Same error.

**Comment by dblock** [comment]
Same token? Are you doing `as_user: true` in the library version of your test? All the library does is that exact post.

**Comment by DannyBen** [comment]
This fails:

`client.chat_postMessage(channel: '#general', text: 'Hello from Ruby Client', as_user: true)`

This succeeds:

`client.chat_postMessage(channel: '#general', text: 'Hello from Ruby Client', as_user: false, username: 'Ruby')`

**Comment by dblock** [comment]
This is by design (of Slack). Your token has a bot user attached to it, so when you say `as_user: true` you're saying post as that attached user. When that user isn't in a channel you can't. But bots can post to all channels because they aren't actual users, they are bots. 

This is fairly convoluted, I would have designed this API differently and use the bot token to obtain the user's token, but we can complain to Slack ;)
