### ISSUE TITLE
Support for sending actions

### ISSUE THREAD

**Issue by danwu** [slack-ruby/slack-ruby-client#143]
Slack API added support for message actions, would be great to have that added as an option when posting message.

https://api.slack.com/docs/message-buttons

**Comment by dblock** [comment]
Note that these are just attachments, so I don't think we need to do anything in this library to enable this.

**Comment by avnerbarr** [comment]
I've tried adding the attachments per this payload

https://api.slack.com/docs/message-buttons

and using this:

 https://github.com/slack-ruby/slack-ruby-client/blob/f7e3bb21fb3438ce72eca10428348ce5ae511cbb/lib/slack/web/api/endpoints/chat.rb 


# @option options [Object] :attachments
#   Structured message attachments.

 to a message :

attObj = ... 
@client.chat_postMessage(channel: channel, text: "message", attachments: attObj, as_user: true)

but it doesn't seem to be sent (I don't see them in slack or the result of the method call)

**Comment by dblock** [comment]
I have a bot that does this:

https://github.com/dblock/slack-market/blob/19b8321dc1aa8ad2958b39a36575553166807d18/slack-market/models/market.rb#L21
https://github.com/dblock/slack-market/blob/e91029289b2ae00d2db4cfc3371210c26eb08856/slack-market/api/endpoints/slack_endpoint.rb#L24
