### ISSUE TITLE
slack-ruby-client enable multiple team support  `slack-ruby-bot-server`

### ISSUE THREAD

**Issue by abgaryanharutyun** [slack-ruby/slack-ruby-client#144]
Hi @dblock can you provide me solution about `slack-ruby-client` i trying use `slack-ruby-client` without  `slack-ruby-bot-server` and `slack-ruby-bot` and I can't connect multiple slack team can you provide mew any solutions? 

Thanks

**Comment by dblock** [comment]
This is a very open-ended question. A single instance of client connects to 1 team. You can manage multiple instances whichever way you want, one of them is slack-ruby-bot-server which uses slack-ruby-bot.
