### ISSUE TITLE
`on_complete': missing_scope (Slack::Web::Api::Error)

### ISSUE THREAD

**Issue by LakomsD** [slack-ruby/slack-ruby-client#150]
Hello Dblock !

Thanks so much for your work (and your contributors!). Finally found how to dig into the gem (I'm quite a newbie sorry), and I can't get how this thing works.

I want to retrieve channel_history but it throw me a missing_scope error, seems like a Slack API error, so I checked the permissions on Slack and they seem to be fine, do I missed it or failed to experiment on options syntax ?

Sample script code
```
Slack.configure do |config|
  config.token = ENV['SLACK_API_TOKEN']
end
client = Slack::Web::Client.new
puts client.channels_history(channel: '#general') #tried 'general' and channel id also
```
Thrown error
`/home/david/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/slack-ruby-client-0.8.1/lib/slack/web/faraday/response/raise_error.rb:9:in `on_complete': missing_scope (Slack::Web::Api::Error)`

Thanks a lot, will be glad to help as soon as I am operational !

**Comment by dblock** [comment]
It's an error from slack that says that the token you're using doesn't have the channels:history scope. Not sure how you obtained the API token, but I am pretty sure this is the problem. See https://api.slack.com/docs/oauth-scopes.

I'll close this, but feel free to add comments/reopen if you are sure your token has the right scope.
