### ISSUE TITLE
invalid_user with users_profile_set

### ISSUE THREAD

**Issue by myf9000** [slack-ruby/slack-ruby-client#152]
I've got **Slack::Web::Api::Error: invalid_user** with users_profile_set method. I have 2 users, and my find_user method (return response with user info) - works well for them. But if I want change status (the same for this cases) - for one user everything is correct, for the second - I've got this error.

Example of call users_profile_set method:
`client.users_profile_set(user: find_user.id, profile: status.to_json)`

My example status hash:
`{:status_text=>"Remote - Today", :status_emoji=>":house_with_garden:"}`

find_user:
`client.users_list.members.find { |member| member.profile.email == user.email }`

What did I do wrong?

**Comment by dblock** [comment]
And the ID is correct and similar looking for both? I mean it's both something like `U...`? If you can reproduce consistently I would open a ticket with slack.

**Comment by myf9000** [comment]
Everything was correct but - option to change user's profile has only on the Paid Plans of Slack
