### ISSUE TITLE
Check Retry-After header

### ISSUE THREAD

**Issue by greggroth** [slack-ruby/slack-ruby-client#153]
I accidentally got rate limited when I enqueued a number of jobs to hit the Slack API and I'm trying to comply with the rate limit, however I don't see any existing means of accessing the `Retry-After` header [mentioned in the docs](https://api.slack.com/docs/rate-limits).  Am I missing something or should I open a PR to better expose this value in the event of a 429 response code?

**Comment by dblock** [comment]
I don't think you missed it. PR welcome. I imagine we should get a specialized exception on a 429?

**Comment by greggroth** [comment]
:+1:  I'll try to put something together over the next few days
