### ISSUE TITLE
Unfurling Links

### ISSUE THREAD

**Issue by cpinky** [slack-ruby/slack-ruby-client#155]
I am having some trouble figuring out how to detect links to unfurl. I am trying to unfurl a link from a private website, but first, i need to detect that link. I have created an app and a bot user. I also do not know how to do the challenge for the request URL in enable events. I am using ngrok. Thanks

**Comment by dblock** [comment]
Could you explain what "detect" means here? Slack's [unfurling docs](https://api.slack.com/docs/message-link-unfurling) don't talk about that.

**Comment by dblock** [comment]
I had to recently implement unfurling, see https://github.com/dblock/slack-strava/commit/dba8cfcb2892e3de9807897b053d7e040849b11e for an example.
