### ISSUE TITLE
Is it possible to catch changing reactions?

### ISSUE THREAD

**Issue by wiiikiii** [slack-ruby/slack-ruby-client#156]
I think about to track a message with reactions on it but I couldn't find out how todo.
Is there a .on "??" I can use?

Thanks

**Comment by dblock** [comment]
Looks like https://api.slack.com/events/reaction_added is what you want.

https://github.com/slack-ruby/slack-ruby-client/blob/684533af2e43561323e55f14ce6ce0eef7b3fadb/lib/slack/real_time/stores/store.rb#L393
