### ISSUE TITLE
Broadcasting thread reply as bot shows up with weird username

### ISSUE THREAD

**Issue by rohitpaulk** [slack-ruby/slack-ruby-client#160]
**Repro script**

```ruby
require 'slack-ruby-client'

Slack.configure do |config|
  config.token = ENV["SLACK_BOT_TOKEN"]
end

client = Slack::Web::Client.new

channel_message = client.chat_postMessage(
  channel: "#general",
  text: "A message in this channel"
)

normal_thread_message = client.chat_postMessage(
  channel: "#general",
  thread_ts: channel_message.ts,
  text: "A message on a thread, but not broadcasted"
)

broadcasted_thread_message = client.chat_postMessage(
  channel: "#general",
  thread_ts: channel_message.ts,
  reply_broadcast: true,
  text: "A message on a thread, broadcasted to channel. *BUG*, Check my username!",
)
```

**Screenshot:** 

![screen shot 2017-08-24 at 12 28 48 pm](https://user-images.githubusercontent.com/3893573/29653593-1af451f6-88c8-11e7-92ef-363fae057bb5.png)

(Note that the bot's username appears as `U00` in the broadcasted message)

I'm not sure if this is specific to the Ruby client, but this seemed a good place to report.

**Comment by rohitpaulk** [comment]
On iOS (iPad), the username appears as 'Member'. 

![image uploaded from ios](https://user-images.githubusercontent.com/3893573/29653835-b3a64ac6-88c8-11e7-9256-1b4fb49e1131.jpg)

**Comment by dblock** [comment]
Could it be a slack bug? Maybe open a help support ticket?

**Comment by rohitpaulk** [comment]
Oh, I didn't realize this repo wasn't affiliated with Slack. I'll open a support ticket. Feel free to close this if you usually don't keep tickets open to track Slack bugs.

**Comment by dblock** [comment]
Happy to help.
