### ISSUE TITLE
Threaded Messaging

### ISSUE THREAD

**Issue by Startouf** [slack-ruby/slack-ruby-client#175]
Hey, I was about to start a chatbot when I realized there was no thread messaging support as reported https://github.com/slack-ruby/slack-ruby-bot/issues/131

I saw no mention of threads at all in the issues of this ruby-client repo, is this feature not available in the Ruby client yet ?

**Comment by jmanian** [comment]
The client supports threading via the `thread_ts` parameter on `chat.postMessage`. I don't know anything about slack-ruby-bot or how it would get integrated at that level, but it's supported at the client level.

**Comment by dblock** [comment]
There's nothing special to do in the client IMO, I'll close this. @Startouf let us know if otherwise.
