### ISSUE TITLE
warning: method redefined; discarding old concurrency

### ISSUE THREAD

**Issue by aadityataparia** [slack-ruby/slack-ruby-client#186]
`/lib/ruby/gems/2.4.0/gems/slack-ruby-client-0.10.0/lib/slack/real_time/config.rb:32: warning: method redefined; discarding old concurrency`
Seems like method concurrency has been defined at two places!

**Comment by dblock** [comment]
That looks like a bug, without any bad side effects but still, would appreciate a fix.

**Comment by aadityataparia** [comment]
One problem I had with this was CI marked test as error, because this warning was shown.

**Comment by dblock** [comment]
@aadityataparia Care to help with a PR?

**Comment by aadityataparia** [comment]
I am not able to find where it is defined before?

**Comment by dblock** [comment]
I am going to reopen this since it looks like a real problem. If you want to fix it @aadityataparia you're more than welcome. Someone else reading this can help too.
