### ISSUE TITLE
Unable to get Slack requests to pass data back to web app when clicking on message buttons

### ISSUE THREAD

**Issue by jaredg8** [slack-ruby/slack-ruby-client#189]
Hi, thanks for making this gem.  I'm trying to build a request web app where a user can accept or reject a request from a user within Slack.  I've been able to get it to post messages to my Slack just fine, however I'm unable to get the Accept or Reject buttons within Slack to pass any kind of data.  Trying this on both local host and ngrok and all I can get is a slackbot/response "Oh no, something went wrong. Please try that again."  Any help would be greatly appreciated.

**Comment by dblock** [comment]
Without seeing the code a lot of things could be wrong. Does it reach your server? I would write a spec for your callback ala https://github.com/dblock/slack-market/blob/master/spec/api/endpoints/slack_endpoint_spec.rb to begin with.

**Comment by jmanian** [comment]
That error message usually means either that the request from Slack isn't reaching your server, or your server is responding with something other than 200. The [dev4slack](http://dev4slack.xoxco.com/) Slack community is a good place to go with issues like this.

**Comment by balaG4046** [comment]
hi can you please share the slack community link, even I'm facing similar issue  like this

**Comment by dblock** [comment]
I'm going to close this issue since it doesn't have any detailed information and dates from 2017.

@balaG4046 if you're having problems feel free to open a new one with all the details if you can't figure it out
