### ISSUE TITLE
Update README.md with http_proxy gotcha

### ISSUE THREAD

**Issue by phantomdata** [slack-ruby/slack-ruby-client#191]
Over in https://github.com/slack-ruby/slack-ruby-bot/issues/155, we identified a minor gotcha with Docker for OSX erroneously setting the `http_proxy` environment variable which ultimately caused Faraday to cough up a seemingly unrelated error about being unable to locate a host (`ERROR -- : Failed to open TCP connection to : (getaddrinfo: Name or service not known) (Faraday::ConnectionFailed)`).

We updated the docs for `slack-ruby-bot`, but this also applies here to `slack-ruby-client` as well.  We should update the README.md to include changes per https://github.com/slack-ruby/slack-ruby-bot/commit/c9ed35549c263cc82eb60a1fe8ec9632af980096 as well.

/cc @phantomdata for assignment and @dblock for tracking.

**Comment by dblock** [comment]
Closed via https://github.com/slack-ruby/slack-ruby-client/commit/83ac106e2e7c54c94486d960aca2584caf903f18.
