### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by manuelmeurer** [slack-ruby/slack-ruby-client#193]
@dblock Could you cut a new gem release? :)
Would love to use the new `users.lookupByEmail` method.
Thanks!

**Comment by dblock** [comment]
I ran `ake slack:api:update` and got a failure in a patch, so looks like this is a bit more work. Care to fix that and make a PR? I can cut a release after.

**Comment by manuelmeurer** [comment]
Seems like the method parsing of https://api.slack.com/methods/chat.postMessage failed, all the arguments were removed: https://github.com/slack-ruby/slack-api-ref/commit/308554474b349feb3bd86f997a4507637ed408a1#diff-294069ad8348d4365db2a6446789d0a5
I'll have a look and try to find out what's wrong.

**Comment by manuelmeurer** [comment]
Slack changed the format of the method doc pages slightly (removed a `<p>`), this is why all arguments were removed in the commit mentioned above. Fixed in https://github.com/slack-ruby/slack-api-ref/pull/27

**Comment by dblock** [comment]
@manuelmeurer Now that slack-api-ref is fixed, make a PR here with updates. It's `slack:api:update` and a proper CHANGELOG. Thanks!

**Comment by manuelmeurer** [comment]
Done: https://github.com/slack-ruby/slack-ruby-client/pull/196

**Comment by dblock** [comment]
@manuelmeurer Want to do the release? What's your rubygems email?

**Comment by manuelmeurer** [comment]
Sure, it's manuel@krautcomputing.com

**Comment by dblock** [comment]
You've been added. Please follow https://github.com/slack-ruby/slack-ruby-client/blob/master/RELEASING.md and close this issue once it's done. Thanks!

**Comment by manuelmeurer** [comment]
Ok thanks! Should the next version be 0.11.1 (noted in the changelog) or 0.12.0? Probably the latter, since we added at least one new method, right?

**Comment by dblock** [comment]
API changes that break things need a major increment, but not additions, so 0.11.1 is fine IMHO

**Comment by manuelmeurer** [comment]
Done! :sparkles:
I missed one update in the README since I misread RELEASING, so I fixed the wording. Hope that's ok!

**Comment by jmanian** [comment]
@manuelmeurer I think you should move the v0.11.1 tag to 6c65430c96ccc6b07e47d0a67a9a21df5e066628, so that if someone looks at the code for the tag it has the correct README for the release.

Also I noticed travis is complaining about something, not sure if that's related to the release.

**Comment by dblock** [comment]
Travis is a fluke I think, something is failing intermittently with faye-websocket. If it happens often I'll open a bug.

**Comment by dblock** [comment]
Thanks for jumping in @jmanian. No strong opinions on tag.

**Comment by dblock** [comment]
https://github.com/slack-ruby/slack-ruby-client/issues/198 for that build problem

**Comment by manuelmeurer** [comment]
@jmanian Good point, tag moved!
