### ISSUE TITLE
Channel Join event

### ISSUE THREAD

**Issue by abgaryanharutyun** [slack-ruby/slack-ruby-client#194]
Hello i went to create channel join event how can write simple code example for channel join? Thanks!!!

**Comment by dblock** [comment]
You mean something that happens when a bot joins a channel? I have an example [here](https://github.com/dblock/slack-gamebot/blob/master/slack-gamebot/server.rb#L17).

**Comment by dblock** [comment]
I'll close this, ask more questions if the example is not clear.
