### ISSUE TITLE
Set initial message on specific channel when users are joined in that channel

### ISSUE THREAD

**Issue by abgaryanharutyun** [slack-ruby/slack-ruby-client#195]
@dblock related this issue #194  I want to send an initial message from API when users joined the specific channel? I want to implement this event https://api.slack.com/events/member_joined_channel from  `slack-ruby-client` package!! Can you set code example or anything else?

**Comment by dblock** [comment]
I don't have a working example, but It's similar to https://github.com/dblock/slack-gamebot/blob/master/slack-gamebot/server.rb#L17, if you can't get it to work post code that doesn't work.

**Comment by dblock** [comment]
Add a comment to this thread if you need to and we'll be happy to help, no need to open a new issue unless its a completely different problem please.

**Comment by abgaryanharutyun** [comment]
@dblock  i need implement this event 
https://github.com/slack-ruby/slack-ruby-client/blob/master/lib/slack/real_time/stores/store.rb#L85

**Comment by abgaryanharutyun** [comment]
@dblock Im tying like this 
```ruby
client = Slack::RealTime::Stores::Store.new(channel_list);
client.on :member_joined_channel  do |data|

end
```
but I can't create an instance because `:Store.new` want to many required parameters I can pass all parameters but I think this is not a good idea

**Comment by dblock** [comment]
That method is on a store class, but that's not how you use it. Do you have a working bot yet that does basic things?

**Comment by abgaryanharutyun** [comment]
Yeah I have a bot who worked, but I want to use `channel_join` event for all members who joined in the channel, do you mean if I use into the bot class `channel_join` event that event returned me for all members who joined the channel?

**Comment by dblock** [comment]
No you should `member_joined_channel`, but you should put that onto the bot class, for example:

```ruby
module MyBot
  class MyServer < SlackRubyBot::Server
    on :member_joined_channel do |client, data|
     # ...
    end
end
```

Show us your code if you can't get it to work.

**Comment by abgaryanharutyun** [comment]
Thanks, @dblock I will try and notice you

**Comment by abgaryanharutyun** [comment]
@dblock thanks that worked awesomely :) 👍
