### ISSUE TITLE
Support for posting ephemeral messages?

### ISSUE THREAD

**Issue by chrismv48** [slack-ruby/slack-ruby-client#199]
Is there any way to post [ephemeral messages](https://api.slack.com/methods/chat.postEphemeral)?

**Comment by alexagranov** [comment]
Yes.  Right here: https://github.com/slack-ruby/slack-ruby-client/blob/master/lib/slack/web/api/endpoints/chat.rb#L94-L106

**Comment by dblock** [comment]
Closing, thanks @alexagranov.

**Comment by chrismv48** [comment]
Ah I see that was only added 5 months ago; guess I need to update! Thanks
