### ISSUE TITLE
Add link_names to files_upload 

### ISSUE THREAD

**Issue by mattblang** [slack-ruby/slack-ruby-client#200]
Through the API tester on the Slack API when uploading a file you can escape a mention like `<!channel>` for the value passed to `initial_comment`. The ruby client for sending a message supports the `link_names` argument, which is nice as it shields you from having to write any escaping logic. Unfortunately though, the `files_upload` method does not support this same argument; based on the official API tester it seems like it would make sense to.

**Comment by dblock** [comment]
Is this a parameter missing in here or in https://github.com/slack-ruby/slack-api-ref? You should track it down back to here.

**Comment by mattblang** [comment]
@dblock Actually, I think I understand why this library does not support it. The `link_names` parameter is supported in the slack API itself for `chat.postMessage`, as apposed to `file.upload` which does not support it. I do feel that `file.upload` should be supported in the Slack API, as you are able to do mentions if they are escaped, but that of course is not an issue for here.

**Comment by dblock** [comment]
You should submit a ticket to slack about it, they pay attention!
