### ISSUE TITLE
Can't use slack-ruby-client because of json version conflicts

### ISSUE THREAD

**Issue by altjx** [slack-ruby/slack-ruby-client#212]
I read through the gem's documentation and absolutely cannot wait to use this gem. However, I do have one issue that I'm experiencing thus far. When I try to use `require 'slack-ruby-client'`, I cannot because of an issue with the json gem and version conflicts.

```
[user:ubuntu:~/Documents]$ irb                                                                                                                  4:43PM/07.08
2.5.1 :001 > require 'slack-ruby-client'
Traceback (most recent call last):
       11: from /home/user/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
       10: from (irb):1
        9: from /home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        8: from /home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        7: from /home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        6: from /home/user/.rvm/gems/ruby-2.5.1/gems/slack-ruby-client-0.11.1/lib/slack-ruby-client.rb:13:in `<top (required)>'
        5: from /home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:90:in `require'
        4: from /home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:90:in `each'
        3: from /home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:91:in `block in require'
        2: from /home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:1434:in `activate'
        1: from /home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:2315:in `check_version_conflict'
Gem::LoadError (can't activate json-1.8.6, already activated json-2.1.0)
2.5.1 :002 > exit
```

I'm assuming this has something to do with my configuration since it's working with others, but I'm just not quite sure where to start. I did try doing a few things with Json already, but any help would be greatly appreciated.

Reference: https://stackoverflow.com/questions/51236244/cant-use-a-gem-because-json-2-1-0-is-activated-but-the-gem-requires-1-8-6

**Comment by dblock** [comment]
I think you are loading global gems here and that's causing all the trouble.

You should be using a Gemfile (create one in an empty folder) that has `gem 'slack-ruby-client'` in it, then run `bundle install` which will bring in compatible dependencies (including whatever version of json). To use it via `irb`, run `bundle exec irb` instead of just `irb`.

I'll close this, but feel free to add more questions.

**Comment by altjx** [comment]
Gotcha. Thanks so much!!!

Regards,
Alton

Sent from my iPhone

On Jul 9, 2018, at 12:30 AM, Daniel Doubrovkine (dB.) @dblockdotorg <notifications@github.com> wrote:

I think you are loading global gems here and that's causing all the trouble.

You should be using a Gemfile (create one in an empty folder) that has gem 'slack-ruby-client' in it, then run bundle install which will bring in compatible dependencies (including whatever version of json). To use it via irb, run bundle exec irb instead of just irb.

I'll close this, but feel free to add more questions.
