### ISSUE TITLE
Ownership is not transferred

### ISSUE THREAD

**Issue by ioquatix** [slack-ruby/slack-ruby-client#222]
I just realised there is another issue.

You call connect, but you don't call close.

https://github.com/slack-ruby/slack-ruby-client/blob/9b848865cf5452030ce0a7618a1640e13ee4696b/lib/slack/real_time/concurrency/async.rb#L60

Ownership is not transferred to the driver/client.

That means calling `driver.close` doesn't call `socket.close`. This is intentional.

If you call `connect` and you don't use a block, you must equally call close somewhere.

```ruby
@socket = build_endpoint.connect
@driver = Client.new(@socket, url)
```

To close the connection:

```ruby
@driver.close
@socket.close
```

Otherwise the underlying socket will be leaked.

My apologies for not mentioning this or providing the correct PR.

**Comment by ioquatix** [comment]
One alternative is to add to your subclass of client, the correct logic, I think it would look something like this:

```
def close
  super
  @socket.close
end
```

**Comment by dblock** [comment]
Thanks, https://github.com/dblock/slack-ruby-client/commit/f2062ece47444b5e81c0f24ba7921530c21b8113

**Comment by dblock** [comment]
@ioquatix I ams still seeing hung up bots that won't restart with this change.

I tried closing the reactor with `reactor.close`, and got `listen loop error: double resume (FiberError)`, consistently.

```
07:39:50 web.1  | I, [2018-09-04T07:39:50.176375 #58616]  INFO -- : dblock: socket closed, restarting ...
07:39:50 web.1  | E, [2018-09-04T07:39:50.315465 #58616] ERROR -- : listen loop error: double resume (FiberError)
07:39:50 web.1  | E, [2018-09-04T07:39:50.316231 #58616] ERROR -- : /Users/dblock/.rvm/gems/ruby-2.3.1/gems/async-1.10.3/lib/async/task.rb:153:in `resume'
07:39:50 web.1  | E, [2018-09-04T07:39:50.317118 #58616] ERROR -- : /Users/dblock/.rvm/gems/ruby-2.3.1/gems/async-1.10.3/lib/async/task.rb:153:in `stop'
07:39:50 web.1  | E, [2018-09-04T07:39:50.317628 #58616] ERROR -- : /Users/dblock/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/set.rb:306:in `each_key'
07:39:50 web.1  | E, [2018-09-04T07:39:50.318213 #58616] ERROR -- : /Users/dblock/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/set.rb:306:in `each'
07:39:50 web.1  | E, [2018-09-04T07:39:50.318751 #58616] ERROR -- : /Users/dblock/.rvm/gems/ruby-2.3.1/gems/async-1.10.3/lib/async/reactor.rb:204:in `close'
07:39:50 web.1  | E, [2018-09-04T07:39:50.319125 #58616] ERROR -- : /Users/dblock/source/slack/slack-ruby-client/dblock/lib/slack/real_time/concurrency/async.rb:59:in `stop_reactor'
```

Terminating the thread instead (https://github.com/dblock/slack-ruby-client/commit/c00e384ba785ee46858945a08e35f107a9d669ef) seems to do ok for now, will keep testing.

**Comment by ioquatix** [comment]
The only thread safe method to stop the reactor is `stop`. Terminating the thread will leak resources. I am currently travelling but will take a look at the code when I have time.

**Comment by dblock** [comment]
Oh yes, that's my bad, `close` -> `stop`.

**Comment by dblock** [comment]
Calling `close` on `@socket` here causes `Async::Wrapper::Cancelled`. 

Is this expected? Do I need to rescue and ignore this?

```
08:11:52 web.1  | E, [2018-09-07T08:11:52.832014 #93162] ERROR -- : The operation has been cancelled! (Async::Wrapper::Cancelled)
08:11:52 web.1  | /Users/dblock/.rvm/gems/ruby-2.3.1/gems/async-1.10.3/lib/async/task.rb:51:in `yield'
08:11:52 web.1  | /Users/dblock/.rvm/gems/ruby-2.3.1/gems/async-1.10.3/lib/async/wrapper.rb:215:in `wait_for'
08:11:52 web.1  | /Users/dblock/.rvm/gems/ruby-2.3.1/gems/async-1.10.3/lib/async/wrapper.rb:102:in `wait_readable'
08:11:52 web.1  | /Users/dblock/.rvm/gems/ruby-2.3.1/gems/async-io-1.15.5/lib/async/io/generic.rb:132:in `async_send'
08:11:52 web.1  | /Users/dblock/.rvm/gems/ruby-2.3.1/gems/async-io-1.15.5/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
08:11:52 web.1  | /Users/dblock/.rvm/gems/ruby-2.3.1/gems/async-websocket-0.6.1/lib/async/websocket/connection.rb:60:in `next_event'
08:11:52 web.1  | /Users/dblock/source/slack/slack-ruby-client/dblock/lib/slack/real_time/concurrency/async.rb:40:in `run_loop'
08:11:52 web.1  | /Users/dblock/source/slack/slack-ruby-client/dblock/lib/slack/real_time/concurrency/async.rb:25:in `connect!'
```
