### ISSUE TITLE
Add websocket-level ping monitoring 

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-client#223]
Ping monitoring in slack-ruby-bot-server checks status of the bot, but https://github.com/faye/websocket-driver-ruby/issues/61#issuecomment-419256695 is saying that we could be sending a ping at websocket level. Which should cause the next read to return a `nil` and abort an offline situation.

**Comment by ioquatix** [comment]
@dblock How are you going with this? I am back in NZ and can take a look at it if you still require assistance.

**Comment by dblock** [comment]
I am not doing any work rn with this. The replacement of celluloid with async has shipped, but did nothing to improve the underlying problem.

**Comment by RodneyU215** [comment]
I started to take a look at this last Friday and I believe I'll have a PR ready for review in a few hours.

**Comment by RodneyU215** [comment]
@ioquatix think you'd be interested in reviewing and weighing in on my approach here #226?

**Comment by dblock** [comment]
Implemented for async-websocket in https://github.com/slack-ruby/slack-ruby-client/pull/226.

**Comment by dblock** [comment]
Implemented for Celluloid and EM in https://github.com/slack-ruby/slack-ruby-client/pull/236.
