### ISSUE TITLE
PR #226 broke integration tests

### ISSUE THREAD

**Issue by RodneyU215** [slack-ruby/slack-ruby-client#231]
There appears to be a missing `async/clock` require statement as well as an issue where the client is not shutting down the reactor when stop is called.

I'm working to fix this now. WIP Branch: [RU_fixing_issue_231](https://github.com/slack-ruby/slack-ruby-client/compare/master...RodneyU215:RU_fixing_issue_231)

**Comment by dblock** [comment]
#226
