### ISSUE TITLE
slack block kit not sending to all users

### ISSUE THREAD

**Issue by nekapoor** [slack-ruby/slack-ruby-client#265]
I have an application that sends messages to users on different slack teams and we're using the new 'blocks' parameter to create these messages. 

And it's working for most users. However, SOME users aren't receiving the block portions of the message. 

Is there a reason why this might be? Is this a slack-ruby-client thing or maybe a slack user setting thing?

**Comment by dblock** [comment]
Unlikely a slack-ruby-client thing. I would debug with help from Slack support. Maybe message too big or something like that?

I'll close this but do reopen if anything points to the library being the problem.
