### ISSUE TITLE
Best practice for bulk direct messages

### ISSUE THREAD

**Issue by problem-child** [slack-ruby/slack-ruby-client#269]
Hi,

Question about bulk sending and the anti flood mechanisms.

I've developed a bot where users to can adhoc query (slash commands) the data we are gathering via separate feeds (external scheduled rake tasks), and to provide scheduled posts about that data to public channels (cron jobs running rake tasks). We've also developed slash commands where users can configure lists of items they are interested in, and they can run bot commands to query these personalised lists.

I'm now looking to put in place instant push notifications in response to changes to the items that are in the users watchlists. There is the potential for a few hundred users to be monitoring an item who would need notifying following an external change. These notifications will need to be sent as a direct message between the bot and the individual users. Given the possibility of running into Slacks anti flooding mechanisms, I was wondering about best practices for this bulk DM send.

My current thinking is rather than sending all the messages in a tight loop calling user.dm!, that I move the user.dm! calls into individual jobs (one per user) to something like Sidekiq so that in a flood fail scenario, the massages can be retried individually and they should all hopefully get through without any duplicates.

Does this sound sensible, or is it possibly overkill. If anybody has has experience sending bulk dm's and has any alternative approaches, I'd be interested to know.

Cheers! 👍

**Comment by dblock** [comment]
You will definitely hit Slack's rate limit, so this sounds sensible.

The library will help you handle 429s from Slack. See [the cursor implementation](https://github.com/slack-ruby/slack-ruby-client/blob/0f5512bf54763f3d81d5dc9e55a0f973eb2b7d08/lib/slack/web/pagination/cursor.rb#L29) that rescues `Slack::Web::Api::Errors::TooManyRequestsError` and waits for the recommended time to avoid resetting that timer.

```ruby
              begin
                response = client.send(verb, query)
              rescue Slack::Web::Api::Errors::TooManyRequestsError => e
                raise e if retry_count >= max_retries

                client.logger.debug("#{self.class}##{__method__}") { e.to_s }
                retry_count += 1
                sleep(e.retry_after.seconds)
                next
              end
```

I suggest rolling out something similar in a background job, but instead of queuing one job per message to have a single worker that pulls the next message to send, sends it, handles 429s as above and loops until there's nothing else to send. 

For my bots I don't bother with another queue and just run them in the same process, eg. [here](https://github.com/dblock/slack-strava/blob/master/slack-strava/app.rb#L15).

```ruby
        once_and_every 10 * 60 do
          brag!
        end
```

```ruby
    def once_and_every(tt)
      ::Async::Reactor.run do |task|
        loop do
          yield
          task.sleep tt
        end
      end
    end
```

Hope this helps. I'll close this issue, but feel free to tack on more questions.

**Comment by problem-child** [comment]
Excellent - I didn't realise there was such easy access to backoff info in the exception.  I'll write a throttling/retry helper function based on the setup of the cursor code you linked to that I can drop the user.dm! calls into via a block. It's going to be much more controlled and manageable handling this in the ruby layer than spamming worker jobs everywhere in the hope them eventually getting through.

Thank you for building such great libraries and for the amazing help!

👍 🍻

**Comment by problem-child** [comment]
Very much a blatant copy of the code above, but I'll leave this here if it's of any use to anybody else. 

You can use it to wrap any slack client calls that might result in flooding and and need a managed retry:

```ruby
  def rate_limit(max_retries=3, forced_sleep=0)
    retry_count = 0
    sleep(forced_sleep)
    loop do
      begin
        return yield #-- Run and return block (assuming it works)
      rescue Slack::Web::Api::Errors::TooManyRequestsError => e
        raise e if retry_count >= max_retries
        logger.info "rate_limit handler: #{e.to_s} - #{e.message}"
        retry_count += 1
        sleep(e.retry_after.seconds)
        next
      end
    end
  end
```

Example Usage:

```ruby
  task :anti_spam_test do
    logger.info "Rake: Start anti_spam_test"

    user = User.first
    (1..1000).each do |i|
      rate_limit { logger.info user.dm! text:"Spam test #{i}" }
    end

    logger.info "Rake: Finish anti_spam_test"
  end
```

Results - No messages dropped. Job stays up:

![image](https://user-images.githubusercontent.com/6280624/57573305-9ee21100-741d-11e9-9ba2-46db8b747452.png)

**Comment by dblock** [comment]
Maybe think about contributing something like this to the library? I think it would be useful to be able to pass in `retry_count: X` into any Slack web API.

**Comment by dblock** [comment]
That feature request is actually already open as https://github.com/slack-ruby/slack-ruby-client/issues/168
