### ISSUE TITLE
chat_update: channel_not_found

### ISSUE THREAD

**Issue by mortee** [slack-ruby/slack-ruby-client#270]
When I try to update an already posted message, no matter how I try, it gives a channel_not_found error back. 
```
[46] pry(main)> client.chat_postMessage channel: 'bot_test_public', text: 'haliho', as_user: true
=> {"ok"=>true,
 "channel"=>"blahblah",
 "ts"=>"1557827217.000500",
 "message"=>{"bot_id"=>"blahblah", "type"=>"message", "text"=>"haliho", "user"=>"blahblah", "ts"=>"1557827217.000500"}}
[47] pry(main)> client.chat_update channel: 'bot_test_public', text: 'hollare ho!', ts: '1557827217.000500'
Slack::Web::Api::Errors::SlackError: channel_not_found
from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/slack-ruby-client-0.14.2/lib/slack/web/faraday/response/raise_error.rb:11:in `on_complete'
```

**Comment by mortee** [comment]
Same happens for chat_delete

**Comment by dblock** [comment]
The only thing I can think of is that if you're doing `as_user` for `postMessage` you also have to do that in `chat_update`. I am doing this [here](https://github.com/dblock/slack-strava/blob/b210a25fd7fef3f071c6017f2f031bdc1108b4a8/slack-strava/models/user.rb#L81) successfully. Is that it?

**Comment by mortee** [comment]
adding as_user: true doesn't solve it either

**Comment by alexagranov** [comment]
While `postMessage` can take a channel name or id, I believe `update` may only know about channel ids.

**Comment by mortee** [comment]
sure, thanks, this didn't cross my mind somehow. fixes my problem

**Comment by dblock** [comment]
Oh I didn't think of that either! Thanks @alexagranov.

**Comment by mortee** [comment]
I was kind of sure something's off here anyway. The README states this:

> You can use a channel ID or name (prefixed with #) in all functions that take a :channel argument. Lookup by name is not supported by the Slack API and the channels_id method called invokes channels_list in order to locate the channel ID.

So ultimately chat_update, chat_delete and the rest are supposed to translate from channel names to IDs automatically, amirite?

**Comment by jmanian** [comment]
I have a theory:

If I recall, this library is built so that if you provide a channel name for a `channel` parameter then it will [attempt to translate the name into an ID](https://github.com/slack-ruby/slack-ruby-client/blob/018dcfdea5a4bfb63310ac16e0dfceb1827816f4/lib/slack/web/api/mixins/channels.id.rb#L14) via a call to `channels.list`. However, in the last year or so Slack has changed `channels.list` to return paginated results, so I think this translation will be failing now, unless the channel happens to be returned in the first page of results.

**Comment by mortee** [comment]
makes sense. also, suxx. slack should at least indicate in their API docs that (as opposed to postMessage) the other methods only accept channel IDs...

> channel | C1234567890 | Required | Channel containing the message to be updated.

**Comment by jmanian** [comment]
Revised theory:

The `channels.*`, `group.*`, `im.*`, and `mpim.*` methods are all considered legacy methods at this point, and [there are now certain channels that will not be supported by these methods](https://api.slack.com/changelog/2018-09-more-reasons-to-be-a-conversations-api-convert). (You're supposed to use `conversations.*` for everything instead.)

So if the channel you're trying to work with is one that is not supported by the legacy method `channels.list`, then this library will fail to translate that channel from a name to an ID. I think this is what you're running into.

I will open a separate issue for this.
