### ISSUE TITLE
Allow file upload with bytes

### ISSUE THREAD

**Issue by mbowen13** [slack-ruby/slack-ruby-client#276]
I am able to upload a file directly from a buffer fo bytes using the Node sdk, but I cannot do this with the Ruby sdk.

Example:
For Node I have a buffer of bytes <Buffer 89 50 4e 47> that I can pass in to files.upload(file: buffer)

But I cannot do the same with a Ruby byte array. I get the error: "invalid_array_arg" 

```
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/slack-ruby-client-0.14.2/lib/slack/web/faraday/response/raise_error.rb:11:in `on_complete'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/faraday-0.15.4/lib/faraday/request/url_encoded.rb:15:in `call'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/faraday-0.15.4/lib/faraday/request/multipart.rb:15:in `call'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/slack-ruby-client-0.14.2/lib/slack/web/faraday/request.rb:25:in `request'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/slack-ruby-client-0.14.2/lib/slack/web/faraday/request.rb:10:in `post'
    /Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/slack-ruby-client-0.14.2/lib/slack/web/api/endpoints/files.rb:142:in `files_upload'
    /Users/michael.bowen/Documents/ops-slackbot/lambdas/fulfillment/lib/slack_wrapper.rb:34:in `post_img'
    /Users/michael.bowen/Documents/ops-slackbot/lambdas/fulfillment/test/slack_wrapper_test.rb:36:in `test_post_img_works'
```

**Comment by mbowen13** [comment]
I got this to work, but only after reading through the Faraday documentation because it wasn't clear in the slack docs what contents: and file: each expect as inputs.

The solution is:
```
file = StringIO.new("\x89PNG\r\n\x1A\n\x00\x00\x00\r")
@client.files_upload(
      channels: '#general,
      as_user: true,
      file: Faraday::UploadIO.new(file, 'image/png'),
      filetype: 'png'
    )
```

To this point I still have no idea how to work around using Faraday for the file: option.

**Comment by dblock** [comment]
We actually have the file option [documented](https://github.com/slack-ruby/slack-ruby-client#upload-a-file). To send a stream of bytes I believe this will work.

```ruby
io = StringIO.new('Test data')
upload_io = Faraday::UploadIO.new(io, 'application/octet/stream')
```
I found this [here](https://github.com/lostisland/faraday/blob/5f55e62e88e5383bf5b2cc92a11f889cfcb29c3a/spec/faraday/request/retry_spec.rb#L157).

Please do contribute to the docs!

**Comment by mbowen13** [comment]
@dblock 
The files_upload() documentation gives no reasoning as to why Faraday::UploadIO is being used in the context of that example. The flag for file: in files_upload() is vague and does not tell you specifically what it wants. Compare this to the [Node docs](https://slack.dev/node-slack-sdk/web-api#upload-a-file) which tells you exactly what it expects. JS is not static typed either, so I see no real excuse for the vagueness in the Ruby client.

I also went digging into the Faraday repo to find a solution...which I think is pretty silly to find a solution in an adjacent repo's unit test....

 I guess the best thing is for me to contribute instead of ranting. Do I submit a PR to just the README, or where else?

**Comment by mbowen13** [comment]
@dblock
Can I submit PR to update the README and flags within the code and any other places in the code to help clarify this issue?

**Comment by dblock** [comment]
> @dblock
> Can I submit PR to update the README and flags within the code and any other places in the code to help clarify this issue?

yes please!
