### ISSUE TITLE
The channel is not returned in the private channel list if it was changed from public to private after creating

### ISSUE THREAD

**Issue by phoenixnghi** [slack-ruby/slack-ruby-client#296]
Steps to reproduce:
1. Create a new public channel
2. Convert it from public to private
3. Invite the bot
4. Fetch the private channel list using this code:
```
slack_client = Slack::Web::Client.new
slack_client.auth_test
slack_client.groups_list.groups.pluck(:name)
```

Result: the channel name is not in the list

If the channel was private from the beginning, it's ok
I don't know where is the root cause, I'm not sure it's the gem or from Slack API

Someone please try reproducing?

**Comment by dblock** [comment]
It's definitely an underlying Slack API question/problem unless `.groups_list` is fetching a page of groups and not all groups? I would check that first, then ask Slack support.

**Comment by haseebeqx** [comment]
This is still happening for me.

**Comment by haseebeqx** [comment]
For anyone looking into this,
you have to use 
```
slack_client.conversations_list(types: 'private_channel').channels
```
to get a list of all private channels

For getting both public and private channels
```
conversations_list(types: 'public_channel,private_channel').channels
```
