### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by jwright** [slack-ruby/slack-ruby-client#302]
Hello.

  My team and I are interested in using the new `views` features of the Slack API. These changes are merged into master and so we have been using the master branch in our Gemfile but I was wondering if there is anything holding up cutting a new gem release. We are not comfortable releasing our current branch using a ref that may not be stable for any reason.

  If there are issues that are holding up a new gem release, and I can be of any help on that, please let me know and I would love to help out!

**Comment by dblock** [comment]
I cut 0.14.6.
