### ISSUE TITLE
user.profiles.get returns error with correct token permissions

### ISSUE THREAD

**Issue by nickslow** [slack-ruby/slack-ruby-client#304]
I am trying to get custom profile fields from Slack profiles and I was having trouble getting it to work through the slack-ruby-client. 

I was able to use the same token through Postman to get the fields with both a POST and a GET.

I also tried adding the following into my code and this worked. 

```
module Slack
  module Web
    module Api
      module Endpoints
        module UsersProfile
          def users_profile_get(options = {})
            options = options.merge(user: users_id(options)['user']['id']) if options[:user]
            get('users.profile.get', options)
          end
        end
      end
    end
  end
end
```

I'm not sure why the POST through the gem would return an invalid_token_type when it didn't through Postman but it might be related to Slack wanting the content type to be `application/x-www-form-urlencoded`.

https://api.slack.com/methods/users.profile.get

**Comment by dblock** [comment]
Sounds fishy. Maybe you can turn this into a VCR spec where one succeeds and the other fails? Then we can compare all the fields and try to narrow it down?

**Comment by nickslow** [comment]
@dblock Looks like it was a simple VCR issue on my side from when I was testing different profiles with access and was a false alarm! Sorry about that but I do appreciate the quick response!
