### ISSUE TITLE
Slack 500 page error handling

### ISSUE THREAD

**Issue by jcheatham** [slack-ruby/slack-ruby-client#306]
Hi!  In the process of interacting with Slack's API, it sometimes has the occasion to return an html 500 status page which then causes a `Faraday::ParsingError` with something like
```
unexpected token at '<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Server Error | Slack</title> <meta name="author" content="Slack"> etc.
```

Since the gem is speccing out its own error namespace, it feels like it'd be more consistent to handle and re-raise something in the `Slack::Web::Api::Error` domain instead.  Thanks!

**Comment by dblock** [comment]
Yes, indeed. On a 500 we should be reporting something other than a parsing error. Please contribute?

**Comment by Deconstrained** [comment]
@dblock I've been looking into where in the stack/middleware to implement a rescue/raise for this, and so far the most straightforward solution is in [Slack::Web::Faraday::Request.request](https://github.com/slack-ruby/slack-ruby-client/blob/master/lib/slack/web/faraday/request.rb#L24-L37).

Do you agree with this approach?

**Comment by dblock** [comment]
Usually these things are handled by middleware, eg. https://github.com/slack-ruby/slack-ruby-client/blob/master/lib/slack/web/faraday/response/raise_error.rb

Start by writing a test and solving the problem in any way you can. We can improve upon it.

**Comment by Deconstrained** [comment]
I had been thinking along those lines as well, but it has been challenging to grok the order of middleware execution.

So, in this PR I built a test and explored a non-`rescue` method of detecting an invalid response and raising. Please let me know what you think:

https://github.com/slack-ruby/slack-ruby-client/pull/307

**Comment by dblock** [comment]
Implemented in https://github.com/slack-ruby/slack-ruby-client/pull/350
