### ISSUE TITLE
chat_PostMessage with Chinese text fails to render

### ISSUE THREAD

**Issue by nguyen-anh-minagine** [slack-ruby/slack-ruby-client#314]
Hi. I have a problem about message error font when send messages with chat_PostMessage.
my message look like.
```ruby
{"channel":"UV550M70FFF","text":"0105：*間*樹さんより、直行直帰・>出張の申請がありました。\nhttp://54.250.35.4423/work/drctgortrnbsnsstripapplymngmnt/link/597?type=a\n\n────────────────────\n◆申請内容\n────────────────────\n申請日時：2020-03-10 17:59:19 +0900\n種　　別：出張届\n行　　先：1\n\n対 象 日：2020/03/10 - 2020/03/10\n出張日数：1\n宿 泊 数：1\n\n\n申請理由：\n1\n\n","attachments":[{"text":"返信可能処理","callback_id":"applied_business_trip","actions":[{"name":"approve","text":"承認","type":"button","value":"597"},{"name":"decline","text":"却下","type":"button","value":"597"}]}]}
```
after sent. I check on my slack team and result like 
![Screen Shot 2020-03-21 at 12 20 03 PM](https://user-images.githubusercontent.com/62244321/77220083-36041300-6b6f-11ea-8432-2aac31c289af.png)

**Comment by dblock** [comment]
Could be a bug. Let's isolate the problem to the library vs. slack.

Try something simpler to start, like basic Chinese text? Can you send a plain message in Chinese and get it rendered?

If it's not working, get it working with `curl`. Then we can see if the library is encoding something wrong.

**Comment by nguyen-anh-minagine** [comment]
@dblock I tried with base text and the results were not much better
```ruby
"0105：*間*樹さんより、直行直帰・>出張の申請がありました"
```
![Screen Shot 2020-03-22 at 11 33 00 AM](https://user-images.githubusercontent.com/62244321/77242457-2816c680-6c31-11ea-8478-af0953003a17.png)

This is response after use chat_PostMessage:
```ruby
channel=D0102JS7WUQ, message=bot_id=BVAS6GENP, bot_profile=app_id=AB150GQ75, deleted=false, icons=image_36=https://a.slack-edge.com/80588/img/plugins/app/bot_36.png, image_48=https://a.slack-edge.com/80588/img/plugins/app/bot_48.png, image_72=https://a.slack-edge.com/80588/img/plugins/app/service_72.png, id=BVAS6GENP, name=minagine dev app, team_id=T1K3LHXJN, updated=1584529025, team=T1K3LHXJN, text=0105BAD+F*BAD+9*BAD+6BAD+3BAD+3BAD+3BAD+3BAD+3BAD+7BAD+8BAD+7BAD+5BAD+3&gt;BAD+5BAD+5BAD+3BAD+7BAD+8BAD+3BAD+3BAD+3BAD+3BAD+3BAD+3, ts=1584851557.000400, type=message, user=UV550M70T, ok=true, ts=1584851557.000400
```

**Comment by nguyen-anh-minagine** [comment]
@dblock I dont know what is the reason. But if i run server by puma, everything run fine. And run by unicorn => error like above

**Comment by dblock** [comment]
This works for me:

```ruby
require 'slack-ruby-client'

client = Slack::Web::Client.new(token: ENV['SLACK_API_TOKEN'])
client.chat_postMessage(channel: '#general', text: '0105：*間*樹さんより、直行直帰・>出張の申請がありました')
```

<img width="499" alt="Screen Shot 2020-03-22 at 11 38 12 AM" src="https://user-images.githubusercontent.com/542335/77253625-cc990880-6c31-11ea-8fc6-50fd086252d9.png">

and works with your example, too

```ruby
require 'slack-ruby-client'

client = Slack::Web::Client.new(token: ENV['SLACK_API_TOKEN'])

request = {:channel=>"#general",
 :text=>
  "0067：*井*志さんより、休暇の申請がありました。\nhttps://a0b495d4.ngrok.io/work/rstapplymngmnt/link/3759?type=a\n\n────────────────────\n◆申請内容\n────────────────────\n申請日時：　　2020-03-22 17:02:34 +0900\n休暇日　：　　2020/04/06\n\n休暇時刻：　　10:00 - 12:00\n\n休暇種別：　　遅刻届\n\n\n休暇理由：\n\n\n備考：\n\n",
 :attachments=>
  [{:text=>"返信可能処理", :callback_id=>"applied_rest", :actions=>[{:name=>"approve", :text=>"承認", :type=>"button", :value=>"3759"}, {:name=>"decline", :text=>"却下", :type=>"button", :value=>"3759"}]}]}

client.chat_postMessage(request)
```

<img width="693" alt="Screen Shot 2020-03-22 at 11 39 37 AM" src="https://user-images.githubusercontent.com/542335/77253658-ffdb9780-6c31-11ea-8f21-368ef43d7334.png">

Is your `request_body` actually a hash? or a JSON string?

**Comment by nguyen-anh-minagine** [comment]
@dblock . I don't know what is the exact reason. But this works for other rails project and without my current project. So i have decided use other Gem(rest-client) and this works.

**Comment by dblock** [comment]
It would be nice to understand what's going on. Could you maybe strip the project to a minimum and upload it to Github?

**Comment by nguyen-anh-minagine** [comment]
@dblock Sorry. This is private project.

**Comment by dblock** [comment]
I encourage you to spend a little bit of extra time, just like I did here, to help the next person, and make an effort to debug it rather than to just drop it. Do your part in open-source.

**Comment by nguyen-anh-minagine** [comment]
@dblock OKE. Let me try.

**Comment by nguyen-anh-minagine** [comment]
@dblock my current project is a complex system. And it is written 10 years ago. SO i don't  know what i strip the project to a minimum.

**Comment by dblock** [comment]
I would write an RSpec test that reproduces the problem, then delete all controllers, views, database access, etc., for as long as the test keeps failing.

**Comment by dblock** [comment]
There was another similar report in #317. One of the possible issues was that text was not UTF-8 encoded. @nguyen-anh-minagine, try `text.encoding` before it gets sent to `chat_postMessage`.
