### ISSUE TITLE
Charset for special characters in messages

### ISSUE THREAD

**Issue by K1N5L4Y3R** [slack-ruby/slack-ruby-client#317]
I'm using `Slack::Web::Client#chat_postMessage` to send a message to a Slack group. However, sometimes the message may contain characters such as "Ñ", "Á", "É", etc. I can see that these letters are not shown in Slack.

When debugging a request, I can see that the following header is sent: `Content-Type: application/x-www-form-urlencoded`. I'm not sure if it is possible or valid to include a charset at the end of this header, or if instead of using this content type we could send JSON to define a charset. Or maybe there's another way to have these characters shown in Slack?

**Comment by dblock** [comment]
This is supposed to work as expected by default.

<img width="373" alt="Screen Shot 2020-04-03 at 10 30 41 PM" src="https://user-images.githubusercontent.com/542335/78416933-f9b6c500-75fa-11ea-88b0-989320b86049.png">

The issue does sounds familiar though. A similar problem was reported in some particular configuration. Do you have a repro that we can see? What's the encoding/locale setup in your system/app/json etc.?

**Comment by K1N5L4Y3R** [comment]
Huh... that's weird. It does work when sending it manually from the console of both my development and production environments.
The only thing that I can think of that could be different from this test, is that when I have seen this issue arise, the message was sent from a Sidekiq worker (but I can't think of a reason why that would matter) 🤔.

I'll keep digging from my side. I'm gonna close this for now so I don't pollute the list of issues. If I find the reason for this 'bug', I'll reopen it to let you know. Thanks for your help.

**Comment by dblock** [comment]
Do you have any repro @K1N5L4Y3R?

**Comment by dblock** [comment]
I think this is as simple as text making it into the client is not encoded UTF-8. 

```ruby
text = 'may contain characters such as "Ñ", "Á", "É"'.encode(Encoding::ISO_8859_1)
p text # => "may contain characters such as \"\xD1\", \"\xC1\", \"\xC9\""
client.chat_postMessage(channel: '#general', text: text, as_user: true)
```

<img width="442" alt="Screen Shot 2020-04-04 at 12 09 42 PM" src="https://user-images.githubusercontent.com/542335/78455613-5d79d600-766d-11ea-8390-5749fff5fb73.png">

**Comment by dblock** [comment]
Do we need to document this? Appreciate a PR that explains that text should be UTF-8.

**Comment by dblock** [comment]
I was bored, so https://github.com/slack-ruby/slack-ruby-client/pull/318

**Comment by K1N5L4Y3R** [comment]
I don't see "BAD+11" or similar instead of the special characters, but just a space. I have tried your snippet and with it I do see "BAD+xx" in Slack.

I will add some logging to my Sidekiq worker which causes this behavior to check:

1.` Encoding.default_external`
2. `Encoding.default_internal`
3. And the actual encoding of the string I'm sending inside the message

, just to check what encoding is being used when sending the message. I will let you know my findings probably later today.

Thanks for looking into this and for the PR.

**Comment by K1N5L4Y3R** [comment]
I have confirmed that the encoding is UTF-8. After investigating I realized that the string in question was saved without the special characters in the database (e.g. `Some test with áÁñÑ` is saved as `Some test with á ñ `)

This confirms that this library is not the culprit.

**Comment by dblock** [comment]
Thanks for following up @K1N5L4Y3R.
