### ISSUE TITLE
No break spaces (\ u00a0) are not decoded before processing

### ISSUE THREAD

**Issue by MichaelM-Shopify** [slack-ruby/slack-ruby-client#319]
Since slack switched to their new text formatting I stumbled across an interesting issue. It looks like slack-ruby-client doesn't currently decode the unicode character for no break spaces `\u00a0`. 

When a slack message that contains linked context (@, #channel, or actual link) and is copied, slack surrounds it with no break spaces. 

This has the end result of copied text passing this no break space on.

An example using slack-ruby-bot I have a command that verifies a domain.

Running `verify domainname.com` works, but if I copy that same text from the chat window to re-run the command it fails. Looking at my debug logs this is because we end up receiving the text from Slack as `verify\u00a0domainname.com`

These no break spaces should really be decoded when we receive them to avoid these situations.

I did lots of debugging with slack support and they said they would expect the libraries to decode the string for unicode before processing it.

**Comment by dblock** [comment]
Interesting ... but it sounds like we do decoding properly, but slack somehow would like the library to always convert `u00a0` into a plain space? Not sure how I feel about the library doing this, but either way I am open to looking at a PR. 

Also, https://stackoverflow.com/questions/4859438/how-do-i-remove-a-non-breaking-space-in-ruby can be relevant.

**Comment by dblock** [comment]
Leaving the text as is in the client, supporting non-breaking spaces in slack-ruby-bot via https://github.com/slack-ruby/slack-ruby-bot/pull/256
