### ISSUE TITLE
Compatibility with conversations API and deprecations on November 25th, 2020

### ISSUE THREAD

**Issue by adrianomedeirossantos** [slack-ruby/slack-ruby-client#320]
Hi everyone,

First of all, this is a great project and it helped me to create bots in Ruby pretty quick 👍 

As you guys can see in https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api, the Slack team has marked all Web API methods in the channels, im, groups, and mpim namespaces as deprecated. The reccomendation is to use `conversations` methods.

Is there any plan to make the ruby client compatible with that?

**Comment by dblock** [comment]
Would appreciate help with these, first by updating https://github.com/slack-ruby/slack-api-ref that can properly reflect any deprecated APIs, then warnings for deprecated APIs in slack-ruby-client and finally removal of those in versions after November 25th, 2020.

**Comment by adrianomedeirossantos** [comment]
How can I proper mark APIs as deprecated? For example, this one https://github.com/slack-ruby/slack-api-ref/blob/master/methods/groups/groups.archive.json?

**Comment by dblock** [comment]
> How can I proper mark APIs as deprecated? For example, this one https://github.com/slack-ruby/slack-api-ref/blob/master/methods/groups/groups.archive.json?

Start by introducing a "deprecated" field into it.  This file is auto-generated by [a rake task](https://github.com/slack-ruby/slack-api-ref/blob/master/tasks/lib/slack_api/methods_spider.rb) by scraping Slack web pages, so assuming the method is marked as deprecated on the web page you should be able to lift it from there and add `"deprecated" : true` into the JSON.

**Comment by wasabigeek** [comment]
@dblock, was trying to run `rake slack:web:api:update` and running into some issues with "patches":
```
...
- patching lib/slack/web/api/patches/chat.1.text-attachments-required.patch
- patching lib/slack/web/api/patches/chat.2.attachments-json.patch
- patching lib/slack/web/api/patches/chat.3.update-attachments-support.patch
error: patch failed: lib/slack/web/api/endpoints/chat.rb:154
error: lib/slack/web/api/endpoints/chat.rb: patch does not apply
rake aborted!
failed to apply patch
...
```
I'm not the most familiar with git patches, what should I do in this case?

**Comment by dblock** [comment]
The path will need to be updated. See https://github.com/slack-ruby/slack-ruby-client/blob/master/CONTRIBUTING.md#patching-slack-web-api to get started.

**Comment by wasabigeek** [comment]
@dblock did I understand right that we can close this? At a glance it seem most of the [alternative methods]( https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api) are already available in the client (albeit auto-generated)

**Comment by dblock** [comment]
I think we can close when #328 is closed. Otherwise users still see deprecation methods in unexpected places.

**Comment by dblock** [comment]
Closing via https://github.com/slack-ruby/slack-ruby-client/pull/331
