### ISSUE TITLE
undefined method `new' for BigDecimal:Class, Ruby 2.7

### ISSUE THREAD

**Issue by geraldeersteling** [slack-ruby/slack-ruby-client#321]
Hello,

I'm trying to use the client in combination with fastlane, this worked fine up till today.

When I try to `require` the gem it immediately crashes with the following exception:

`NoMethodError: [!] undefined method `new' for BigDecimal:Class`

The complete stack trace is as follows:

```
bundler: failed to load command: fastlane (/Users/REDACTED/.gem/ruby/2.7.0/bin/fastlane)
NoMethodError: [!] undefined method `new' for BigDecimal:Class
  /Users/REDACTED/.gem/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object.rb:3:in `require'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext.rb:2:in `require'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext.rb:1:in `each'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext.rb:1:in `<top (required)>'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/slack-ruby-client-0.14.4/lib/slack-ruby-client.rb:39:in `require'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/slack-ruby-client-0.14.4/lib/slack-ruby-client.rb:39:in `<top (required)>'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/fastlane_require.rb:10:in `require'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/fastlane_require.rb:10:in `install_gem_if_needed'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/fast_file.rb:232:in `fastlane_require'
  Fastfile:55:in `block in parsing_binding'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:290:in `execute_flow_block'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/REDACTED/.gem/ruby/2.7.0/gems/fastlane-2.146.1/bin/fastlane:23:in `<top (required)>'
  /Users/REDACTED/.gem/ruby/2.7.0/bin/fastlane:23:in `load'
  /Users/REDACTED/.gem/ruby/2.7.0/bin/fastlane:23:in `<top (required)>'
```

I've got no clue how to fix this, but maybe someone can help me out?

**Comment by dblock** [comment]
It's failing to load activesupport. I think you need to lock a different version of `big-decimal`, see [this](https://stackoverflow.com/questions/60226893/rails-nomethoderror-undefined-method-new-for-bigdecimalclass)?

**Comment by dblock** [comment]
This is well understood and explained in https://github.com/ruby/bigdecimal/issues/127. Update `big-decimal` to 2.5.5+ and the issue should go away.

**Comment by geraldeersteling** [comment]
Right, I've checked both of those posts you mentioned. But I can't find a [higher version of bigdecimal as 2.0.0](https://rubygems.org/gems/bigdecimal).  
Can I ask which ruby version and `bigdecimal` version you're using then?

I came to ask here because it's literally this gem that's the only one which crashes...

**Comment by dblock** [comment]
> Right, I've checked both of those posts you mentioned. But I can't find a [higher version of bigdecimal as 2.0.0](https://rubygems.org/gems/bigdecimal).
> Can I ask which ruby version and `bigdecimal` version you're using then?
> 
> I came to ask here because it's literally this gem that's the only one which crashes...

Hmmm. Do you have a repro? I can take a look.

**Comment by geraldeersteling** [comment]
I was _just_ typing a response 😄 

After trying many things I resorted to reverting back to ruby 2.6+ and bigdecimal 1.4.1, this solved the issue for now and I can safely `require` the gem again.

I guess the culprit was ruby 2.7+ , somehow things broke and I've got no clue how to fix them except for reverting back.

Anyhow, thanks for responding!

**Comment by dblock** [comment]
If you want to help, add Ruby 2.7 in .travis.yml to this project? Let's see if it breaks this way?

**Comment by geraldeersteling** [comment]
Ah, I don't use travis—I'm working with GitLab's CI in a private self hosted environment...

**Comment by dblock** [comment]
I mean for this project, slack-ruby-client. Please PR!

**Comment by geraldeersteling** [comment]
Ah, I see! Sure, it might be a good one to test against 2.7.  
That said, I've got no clue whatsoever regarding the setup for this project and/or travis. I'd be hard pressed to add it myself. 😄

**Comment by dblock** [comment]
> Ah, I see! Sure, it might be a good one to test against 2.7.
> That said, I've got no clue whatsoever regarding the setup for this project and/or travis. I'd be hard pressed to add it myself. 😄

You can get your feet wet here and I'll help if you need it.

**Comment by geraldeersteling** [comment]
Will try to add a PR then when I have the chance!

**Comment by dblock** [comment]
I'll reopen this to get Ruby 2.7 support.

**Comment by Charaoh** [comment]
Any luck trying to fix this issue?

**Comment by dblock** [comment]
See https://github.com/slack-ruby/slack-ruby-client/issues/321#issuecomment-623441987, upgrade BigDecimal and the problem will go away. We also added 2.7 to CI.

**Comment by vignesh-drg** [comment]
I am facing the same issue with Ruby 2.7.5 and big decimal 1.4.2.
.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>': undefined method `new' for BigDecimal:Class (NoMethodError)

**Comment by vignesh-drg** [comment]
@dblock - I tried, but the same issue. 
I am upgrading Ruby version 1.9.3 to 2.7.5 for my Sinatra application and getting the same issue after adding to the gem file

**Comment by dblock** [comment]
Too much work for me, put up a repro up on GitHub or something public if you want me to try and look into it
