### ISSUE TITLE
Change APP icon and name while posting the message via webhook

### ISSUE THREAD

**Issue by rohitbansal0689** [slack-ruby/slack-ruby-client#330]
I have created the slack app and webhook inside it. I am able to post a message in the channel attached to webhook.  I would like to change the APP Icon and Name. 

There are options that I can pass in **legacy Incoming Webhooks** but this integration will be deprecated and possibly removed in the future from slack.

How can I change the APP Icon and Name while posting the message via webhook crested inside the app?

Thanks

**Comment by rohitbansal0689** [comment]
Any help here will be appreciated? Thanks

**Comment by dblock** [comment]
This seems like a question for Slack. This is in the bot's profile information I believe, AFAIK there's no API to change the icon or name.
