### ISSUE TITLE
Set Max Retries for users_lookupByEmail and other methods. 

### ISSUE THREAD

**Issue by reedkerma1** [slack-ruby/slack-ruby-client#332]
Hey There,

I am having an issue where when certain slack_client methods are called, and return exceptions, I see the server keeps trying to execute the method over and over -- with what I'm sure are some standard time interval in between I'm guessing. I've tried handling these exceptions by rescuing the error, in hopes that it would "give up" / not retry, but alas it still keeps trying. 

A practical example is when you look up user by email, but no email matches, (returns: `Slack::Web::Api::Errors::UsersNotFound: users_not_found`)  it just keeps trying. I want it to not retry (or at least limit it to 1 or 2 retries) because my logic is -- if the email doesn't exist, it will never exist. 

Is there a way to configure the max retries for various methods? For example, in the two methods below, is there a way to indicate to only try once? if so what would that syntax look like? 

```
      slack_client.chat_postMessage(
        channel: slack_user.id,
        text: greeting_message,
        as_user: true,
        attachments: survey_greeting[:attachments]
      )
```

```
slack_user = Rails.configuration.slack_client.users_lookupByEmail(
        email: @agent_email
      ).user
```

Thank you :)

**Comment by dblock** [comment]
Paginated methods [support retries](https://github.com/slack-ruby/slack-ruby-client/blob/7494411d04fe3127c2809eae81180886bd1f014b/lib/slack/web/pagination/cursor.rb#L31), and is [documented](https://github.com/slack-ruby/slack-ruby-client#pagination-support). However, `users_lookupByEmail` is [not paginated](https://github.com/slack-ruby/slack-ruby-client/blob/6b559c34b22d18910f6ec950c6e2cc2e40239d2a/lib/slack/web/api/endpoints/users.rb#L109). So not sure what is retrying, I think this needs debugging.

**Comment by reedkerma1** [comment]
thanks for the speedy response! 

Ok, its good to rule out one aspect of it at least. I will try your suggestion to further debug my code.

**Comment by dblock** [comment]
Let us know what you find. I'll close this for now.
