### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-client#335]
If you want a release, add your +1.

**Comment by CrazyOptimist** [comment]
+1 here

**Comment by reedkerma1** [comment]
+1

**Comment by dhurba87** [comment]
+1

**Comment by dblock** [comment]
Currently `rake slack:api:update` is failing. If someone wants to fix that and PR an API update I'm happy to release v. next following that.

**Comment by DougEdey** [comment]
@dblock (new to the repo here), I tried to run `rake slack:api:update` and had no issues locally, I don't see it as part of the Release procedure, do you have any details on the issue you're seeing?

(I'm looking to get hold of the updated API for the org level apps (auth_teams_list primarily)

**Comment by dblock** [comment]
I will wait for @wasabigeek to finish https://github.com/slack-ruby/slack-ruby-client/pull/357

**Comment by dblock** [comment]
Released 0.16.0.
