### ISSUE TITLE
Channel_not_found in new conversations_list usage

### ISSUE THREAD

**Issue by Bartlebyy** [slack-ruby/slack-ruby-client#337]
## Problem
On the latest release of 0.15.0 (I upgraded due to the deprecated channels_list to use the new conversations_list) I'm seeing an error when I try to query by a channels name rather than a channel_id. I expect to be able to just `client.conversations_setTopic({:channel => '#channel_name', :topic => 'random topic})` <- but the hashtag channel name format no longer works and only the channel_id approach works.

I find that the code is much more readable with channel names than ids, so please help!

![image](https://user-images.githubusercontent.com/6975256/89197641-05e76a80-d57a-11ea-8472-139193666eac.png)

**Comment by dblock** [comment]
That seems odd as https://api.slack.com/methods/conversations.info is a direct replacement for channels.info. What kind of channel is this (public? private DM?). 

Try calling `conversations_info(channel: '#channel_name')`, do you get this error? Try without a `#`, then try with the ID (that must work), then try again with `channels_info` for all the same. Let us know what you see?

**Comment by Bartlebyy** [comment]
I tested with two channel names, both public. I tested with and without the hashtag, didn't work.

conversations_info with channel name
![image](https://user-images.githubusercontent.com/6975256/89202012-56fa5d00-d580-11ea-91bb-36d670f8f962.png)

without hashtag
![image](https://user-images.githubusercontent.com/6975256/89202257-ab054180-d580-11ea-94f4-c2e89e9832df.png)

and I tested again with the channel_id and it works

**Comment by dblock** [comment]
You should open a ticket with Slack and see what they say. AFAIK it was never documented that you could supply a channel name, but would be nice to know that they explicitly deprecated this, and I would like to know what users should do to translate a channel name into an ID.

We changed this in https://github.com/slack-ruby/slack-ruby-client/pull/331, cc: @wasabigeek - I presume we did test this IRL?

**Comment by wasabigeek** [comment]
@dblock 😨  I did not, will take a look

**Comment by wasabigeek** [comment]
@Bartlebyy could I trouble you to check the result of `conversations_list.channels`? Do the results include the names of each channel? Would be great if you could share an example (anonymised is fine) of the result, something like `conversations_list.channels.map(&:to_h)`.

**Comment by wasabigeek** [comment]
@Bartlebyy any update on this?

**Comment by Bartlebyy** [comment]
@wasabigeek yes, it returns a name attribute. Here's a small snippet with anonymized data. I grabbed the first 2 channels.

```
created=1514966545, creator=CREATOR_ID, id=ID, is_archived=false, is_channel=true, is_ext_shared=false, is_general=true, is_group=false, is_im=false, is_member=false, is_mpim=false, is_org_shared=false, is_pending_ext_shared=false, is_private=false, is_shared=false, name=general, name_normalized=general, num_members=x, parent_conversation=, pending_connected_team_ids=[], pending_shared=[], previous_names=[], purpose=creator=, last_set=0, value=Channel message, shared_team_ids=["TEAM_ID"], topic=creator=ID, last_set=1566994107, value=Value copy, unlinked=0
14:28:45 web.1    | created=1415966621, creator=CREATOR, id=ID, is_archived=true, is_channel=true, is_ext_shared=false, is_general=false, is_group=false, is_im=false, is_member=false, is_mpim=false, is_org_shared=false, is_pending_ext_shared=false, is_private=false, is_shared=false, name=test, name_normalized=test, num_members=0, parent_conversation=, pending_connected_team_ids=[], pending_shared=[], previous_names=[], purpose=creator=ID, last_set=1414966625, value=Channel message, shared_team_ids=["ID"], topic=creator=, last_set=0, value=, unlinked=0
```

**Comment by wasabigeek** [comment]
@Bartlebyy, unfortunately I wasn't able to replicate this, using `client.conversations_setTopic({ channel: '#slack-ruby-client', topic: 'test' })` works for me.

Could I ask for your help again to:
- check that the channel name is correctly invoked in `#conversations_setTopic`
- check that the desired channel name is returned as part of `client.conversations_list.channels.map(&:name)`
- share your Ruby and Gemfile.lock versions (especially for the following:)
```
slack-ruby-client (0.15.0)
      faraday (>= 1.0)
      faraday_middleware
      gli
      hashie
      websocket-driver
```
- are you using any [legacy tokens](https://api.slack.com/legacy/custom-integrations/legacy-tokens) or the new Slack apps?

**Comment by Bartlebyy** [comment]
@wasabigeek we definitely have over 300 public channels

**Comment by dblock** [comment]
> @Bartlebyy does your team have >100 public channels? I was investigating further and it seems we only search the first page of results for both `channels_list` (the docs aren't clear what the default limit is) and `conversations_list` (the default limit is 100) - could you help to confirm this while checking the results of `client.conversations_list`? I think you can look in `client.conversations_list.response_metadata` for a cursor, which means there are more results that are not being returned.

That would be a bug ...

**Comment by wasabigeek** [comment]
Yup, it would be helpful if we can confirm this is the reason why the channels are not found.

**Comment by dblock** [comment]
Fix in https://github.com/slack-ruby/slack-ruby-client/issues/337, @wasabigeek care to CR?

**Comment by dblock** [comment]
@Bartlebyy care to try HEAD now that https://github.com/slack-ruby/slack-ruby-client/pull/339 was merged?
