### ISSUE TITLE
undefined method `users_conversations'

### ISSUE THREAD

**Issue by dfeinberg5** [slack-ruby/slack-ruby-client#345]
I'm trying to call the `users_conversations` method, but keep getting the error `undefined method 'users_conversations'`. I have no idea why, since other endpoints are working fine.

Here's the abbreviated code:
```
@client = Slack::Web::Client.new(token: current_user.token)
@client.auth_test

if @client
  @conversations = @client.users_conversations(user: current_user.uid)
end
```

Slack documentation: https://api.slack.com/methods/users.conversations

slack-ruby-client endpoint: https://github.com/slack-ruby/slack-ruby-client/blob/6b559c34b22d18910f6ec950c6e2cc2e40239d2a/lib/slack/web/api/endpoints/users.rb

Does anyone know why this might be happening? Any help is appreciated :)

**Comment by dblock** [comment]
Which version? Looks like it was added in 0.12.0. 

Post the exception stack?

**Comment by dfeinberg5** [comment]
Thanks @dblock! Can't believe I missed that. I was on an earlier version 🤦 .
