### ISSUE TITLE
Handling interactive messages

### ISSUE THREAD

**Issue by dfeinberg5** [slack-ruby/slack-ruby-client#346]
Hey @dblock,

Do you have an example of how to handle and respond to [interactive messages](https://api.slack.com/interactivity/handling)?

I'm building a Rails app and have been scouring the internet, but can't seem to find much direction.

So far I have:
1. Created an interactive message with a button
2. Published the interactive message
3. Specified an interactivity request url in the Slack admin dashboard

When I hit the endpoint I receive a 403 Forbidden and I'm not really sure where to go from there.

I've also tried adding `skip_before_action :verify_authenticity_token` to my controller, but still receive the 403.

I see that in your docs you mention the Events API, but from what I can see on Slack, events are handled separately from interactivity.
<img width="596" alt="image" src="https://user-images.githubusercontent.com/4513471/93690073-6edf5f00-faa2-11ea-90e5-372e7d4e5386.png">

I'm fairly new to receiving and verifying an external post request, so not sure exactly how to proceed. Any guidance would be amazing!

**Comment by dfeinberg5** [comment]
I discovered that the issue was due to ngrok, so I added `config.hosts << "xxxxxx.ngrok.io" to `config/environments/development.rb`.

So I guess I don't need anything from the slack-ruby-client to handle this. With `skip_before_action :verify_authenticity_token` in place I can just check for the payload in the params.

**Comment by dblock** [comment]
You might want to check out https://github.com/slack-ruby/slack-ruby-bot-server and https://github.com/slack-ruby/slack-ruby-bot-server-events that makes this easier.
