### ISSUE TITLE
Question: 0.15.2 version release? 

### ISSUE THREAD

**Issue by reedkerma1** [slack-ruby/slack-ruby-client#352]
Hey there, 

Wondering when we can expect to see 0.15.2 version released? Really excited to see the new admin endpoints added https://github.com/slack-ruby/slack-ruby-client/pull/348 and would love use slack-ruby-client to access those endpoints! 

Thanks for all the work ya'll put into this!

**Comment by dblock** [comment]
Add a +1 to https://github.com/slack-ruby/slack-ruby-client/issues/335. Will do a release soon, but also other maintainers can without asking :)
