### ISSUE TITLE
500 errors raise a ParsingError rather than an UnavailableError

### ISSUE THREAD

**Issue by agrobbin** [slack-ruby/slack-ruby-client#358]
When upgrading to v0.16, I was expecting that all 500 errors would start raising an `UnavailableError` (thanks to #350). However, if the response is a 500 *and* includes HTML rather than JSON, you still receive a `Slack::Web::Api::Errors::ParsingError`.

Consider this WebMock'd request, which is based on a real-world scenario we ran into when the Slack API was down:

```ruby
WebMock.stub_request(:post, 'https://slack.com/api/chat.postMessage').
  to_return(
    status: 500,
    body: <<~HTML
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <title>Server Error | Slack</title>
          <meta name="author" content="Slack">
        </head>
        <body></body>
      </html>
    HTML
  )
```

Before v0.16 (and #350), this raised a `Faraday::ParsingError` exception, and after those changes, it raises a `Slack::Web::Api::Errors::ParsingError` exception.

Looking further at the tests in #350, it appears while there is a test for [`status: 500, body: '{}'`](https://github.com/slack-ruby/slack-ruby-client/pull/350/files#diff-93bc39d0b2c86aa39fd163c47794a662f568ab6f7b3afa7d790d3e19d03f0dfcR324-R332), and there is a test for [`status: 200, body: '<html></html>`](https://github.com/slack-ruby/slack-ruby-client/pull/350/files#diff-93bc39d0b2c86aa39fd163c47794a662f568ab6f7b3afa7d790d3e19d03f0dfcR291-R300), there is no test for the combination of the 2.

This seems like a bug, but before I went through the process of forking + making a PR, I wanted to raise it and get some feedback from the maintainers of this gem!

**Comment by dblock** [comment]
It sounds like you're right. Slack returns all kinds of things in different scenarios and we just didn't catch this one.

**Comment by agrobbin** [comment]
Thanks @dblock! I will try and get a PR to better handle this scenario later this evening or tomorrow.
