### ISSUE TITLE
Request to downgrade Faraday dependency

### ISSUE THREAD

**Issue by DDmitryS** [slack-ruby/slack-ruby-client#364]
Hello Slack Team,

I'm not sure that the issue is reasonable for most of auditory but our team faced a real problem recently. We have an internal app that do a lot of useful work in our workspace, such as facilitate cross review, scan channels with prod bugs, collect and post jira tickets statistics etc. That means that we have to use both slack-ruby-client and [tinybucket](https://github.com/hirakiuc/tinybucket) gems for our needs.

A few days ago new updates of a gem was coming that contains some deprecated methods. Unfortunately, upgrade led to conflict with faraday dependancy versions. In accordance with your requirements faraday should be (>= 1.0) but it is incompatible with (~> 0.9) in tinybucket. Do we have any chances to see downgrade of faraday requirements or any workarounds about that?

Please feel free to point me to any official doc or share some recommendations/best practices around this.

Thank you very much for your time and attention!

**Comment by dblock** [comment]
This kind of incompatibilities are common. I would recommend upgrading tinybucket's dependency rather than downgrading slack-ruby-client's. You're welcome to maintain a fork if you do the latter, too.
