### ISSUE TITLE
The method chat.postMessage does not support input text fields

### ISSUE THREAD

**Issue by juliofalbo** [slack-ruby/slack-ruby-client#367]
Hi.

I'm trying to send an interactive message where the user will input some data in a text field, but as far as I understood from the [Slack doc ](https://api.slack.com/reference/block-kit/block-elements#input) it is not possible to sent this kind of message via `chat.postMessage`.

Note: I already enabled my Slack App to support interaction.

Here is an example of a message that I want to send.

```
"blocks": [
		{
			"type": "image",
			"image_url": "https://i1.wp.com/thetempest.co/wp-content/uploads/2017/08/The-wise-words-of-Michael-Scott-Imgur-2.jpg?w=1024&ssl=1",
			"alt_text": "test"
		},
		{
			"block_id": "answer",
			"type": "input",
			"element": {
				"type": "plain_text_input",
				"action_id": "initial_code",
				"placeholder": {
					"type": "plain_text",
					"text": "Enter text code, example: 42"
				}
			},
			"label": {
				"type": "plain_text",
				"text": "Enter text on the image"
			}
		}
	]
```

When I send it using the `chat.postMessage` I'm getting this answer:

```
[ERROR] unsupported surface for input block [json-pointer:/blocks/1]"
```

So, what is the solution, using this client, for my situation?

**Comment by dblock** [comment]
This is really a Slack question. From my limited understanding these can be triggered as interactive events, such as slash commands? In which case you want something like https://github.com/slack-ruby/slack-ruby-bot-server-events

**Comment by juliofalbo** [comment]
Amazing, that's exactly what I'm looking for, thanks!
