### ISSUE TITLE
Add openid api support

### ISSUE THREAD

**Issue by ro31337** [slack-ruby/slack-ruby-client#389]
(feature request)

There is OpenID API that allows to read user email address, like https://api.slack.com/methods/openid.connect.userInfo

It's one of the most popular things that you always need - read email address. Should be added IMO.

**Comment by dblock** [comment]
You can help! See https://github.com/slack-ruby/slack-ruby-client/blob/master/CONTRIBUTING.md#update-slack-web-api

**Comment by dblock** [comment]
Updated in https://github.com/slack-ruby/slack-ruby-client/pull/393
