### ISSUE TITLE
Unable to upload xlsx file

### ISSUE THREAD

**Issue by NBuhinicek** [slack-ruby/slack-ruby-client#396]
Been trying to upload a xlsx file but the end result in slack is not what I expected.

<img width="595" alt="test xlsx" src="https://user-images.githubusercontent.com/42773765/152137688-09c61cce-6e7b-4895-8130-d07671eaef12.png">

Here is my code, almost the same as the one in the README 

```ruby
file = Faraday::UploadIO.new(
  'test.xlsx', 
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
)

client.files_upload(
  channels: '#general', 
  file: file, 
  filetype: 'xlsx',
  filename: 'test',
  title: 'Xlsx test', 
  initial_comment: 'Check xlsx upload'
)
```

Been using the same code for pdf and csv upload (while changing mime_type, filetype and the file) and it was working fine.

**Comment by dblock** [comment]
Maybe something slack-side?

**Comment by NBuhinicek** [comment]
Contacted them now, will write back to you when I have more information

**Comment by duffn** [comment]
It doesn't appear to be possible to generate a preview when uploading via the API per https://github.com/slackapi/python-slack-sdk/issues/991#issuecomment-814481675

**Comment by duffn** [comment]
I think this can be closed. This isn't the library but the API itself. It exhibits the same behavior using the API directly.

```
curl -F file=@test.xlsx -F "initial_comment=Test xlsx" -F channels=C0000000 -H "Authorization: Bearer $SLACK_API_TOKEN" https://slack.com/api/files.upload
```
<img width="559" alt="Screen Shot 2023-03-15 at 10 38 19 AM" src="https://user-images.githubusercontent.com/3457341/225378865-64f172e6-8bf5-403d-aa6a-ed01e2d0524f.png">
