### ISSUE TITLE
Conversations List not working when asking for both public and private channels

### ISSUE THREAD

**Issue by alex-benoit** [slack-ruby/slack-ruby-client#397]
`slack_client.conversations_list(types: 'public_channel,private_channel', exclude_archived: true)` only returns public channels but should return both public and private channels as defined [here](https://api.slack.com/methods/conversations.list)

`slack_client.conversations_list(types: 'private_channel', exclude_archived: true)` does return private channels but `public_channel,private_channel` only public channels

**Comment by dblock** [comment]
1. Check whether the client passes these through correctly to Slack, there's no code in the client that alters `types`, so I expect it to. If that's the case, contact slack because their doc seems to say this should "just work".
2. Would be nice if the client accepted an array for `types`.

**Comment by alex-benoit** [comment]
You are right when using https://api.slack.com/methods/conversations.list/test with the correct type mentioned in the docs, it also only returns the public channels. Submitted a bug report will report back.

**Comment by n-sviridenko** [comment]
but is still there btw
