### ISSUE TITLE
Bookmarks API

### ISSUE THREAD

**Issue by kwent** [slack-ruby/slack-ruby-client#398]
Hi,

Since https://api.slack.com/apis/bookmarks-api is not generally available, i think this client should support it :)

Regards

**Comment by dblock** [comment]
Please contribute, see https://github.com/slack-ruby/slack-ruby-client/blob/master/CONTRIBUTING.md#update-slack-web-api.

**Comment by etiennechabert** [comment]
Hello @dblock, thanks a lot for your contribution with this [https://github.com/slack-ruby/slack-ruby-client/commit/bac9c5fec8b08704bbf9884a1aacbd1351bdd197](commit), adding `bookmarks_*` commands 🎉 

Any idea when a new version of this gem would be released? Allowing us to benefit from this new feature? Thanks!

**Comment by dblock** [comment]
I'll do a release soon. Since this was added, closing.
