### ISSUE TITLE
Random Slack::Web::Api::Errors::TimeoutError on chat_update

### ISSUE THREAD

**Issue by benoittgt** [slack-ruby/slack-ruby-client#412]
Hello

I do
```ruby
sentry_client.chat_update(
      channel: channel,
      ts: ts,
      attachments: attachments,
      username: SLACK_USERNAME,
      icon_emoji: SLACK_ICON_EMOJI,
    )
```

And I see in logs that we do a https://github.com/slack-ruby/slack-ruby-client/blob/c50662e837cb5f4e272bce966d702b30222a94dd/lib/slack/web/api/endpoints/conversations.rb#L240
that sometimes lead to timeout.

The thing is I have around between 100 to 250 timeouts per day even with:
```
Slack::Web::Client.configure do |config|
  config.timeout = 40
  config.open_timeout = 40
end
```

And all my Slack calls are made from Sidekiq worker with 10 retries. 

I am wondering if I am the only one?

**Comment by benoittgt** [comment]
Hello

Thanks a lot for the quick answer. Yes it is a channel name. Sometimes I have also the issue with `auth_test` but less often.

I will open a PR to add some documentation on this aspect, and will store locally the channel id when I have it in my app.

**Comment by dblock** [comment]
Closing this since the timeout is "expected".
