### ISSUE TITLE
SSL Error on Heroku-22: SSL_CTX_load_verify_file: system lib

### ISSUE THREAD

**Issue by irphilli** [slack-ruby/slack-ruby-client#415]
On [Heroku-22](https://devcenter.heroku.com/articles/heroku-22-stack) (based on Ubuntu 22), I get the following error when trying to use the client:

```
SSL_CTX_load_verify_file: system lib
```

Something as simple as this causes the error:
```
Slack::Web::Client.new(token: 'abc').auth_test
```

Doing the following is a workaround:
```
Slack::Web::Client.new(token: 'abc', ca_file: nil, ca_path: nil).auth_test
```

Looking at the source, it looks like the gem is defaulting to `OpenSSL::X509::DEFAULT_CERT_FILE` and `OpenSSL::X509::DEFAULT_CERT_DIR`. On Heroku-22, at least, these paths aren't valid.

Any reason for defaulting to those, as opposed to `nil`? (i.e. let OpenSSL figure out the paths).

**Comment by dblock** [comment]
No good reason AFAIK. I say we either document it or change it with a major version bump. Care to PR either?
