### ISSUE TITLE
Faraday::SSLError (SSL_CTX_load_verify_file: system lib)

### ISSUE THREAD

**Issue by yurikoval** [slack-ruby/slack-ruby-client#418]
Using Heroku for deployment. Default `ca_path` does not seem to propagate, and I have to override client settings to make it work. According to [Faraday's docs](https://github.com/lostisland/faraday/wiki/Setting-up-SSL-certificates), `SSL_CERT_FILE` should be observed, but my guess is that 's being overwritten to `nil` in [Slack::Web::Config.reset](https://github.com/slack-ruby/slack-ruby-client/blob/master/lib/slack/web/config.rb#L27-L28).

Was able to do a workaround with the following:

Override client setting:
```ruby
Slack::Web::Client.configure do |config|
  config.ca_file = ENV["SSL_CERT_FILE"]
end
```

Then set SSL cert file location via ENV var: `heroku config:set SSL_CERT_FILE="/usr/lib/ssl/certs/ca-certificates.crt"`

**Comment by dblock** [comment]
I believe this was fixed in https://github.com/slack-ruby/slack-ruby-client/pull/416, but not released, can you please confirm?

**Comment by yurikoval** [comment]
Cool. Looks like it's fixed in the upcoming version.
