### ISSUE TITLE
Integration tests broken

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-client#426]
Looks like we broke integration tests that only run with a token on master.

https://github.com/slack-ruby/slack-ruby-client/actions/runs/3274143367/jobs/5387272594

cc: @kstole

**Comment by kstole** [comment]
I'm not sure what exactly broke the test (if I'm reading correctly, seems like something with `console/progress.rb` in `webmock/rspec`) but I was able to reproduce locally by switching to Ruby 2.7.1 (it passes on 2.7.6). I think we can just update to the latest 2.7 patch.

**Comment by dblock** [comment]
@kstole Right on. It's expecting some console output and that now spit other things out. Closing via https://github.com/slack-ruby/slack-ruby-client/pull/427.
