### ISSUE TITLE
Can't set custom field with #users_profile_set

### ISSUE THREAD

**Issue by anton-smagin** [slack-ruby/slack-ruby-client#430]
I'm trying to change custom field of slack user following official documentation

https://api.slack.com/methods/users.profile.set#custom_profile

```ruby
::Slack::Web::Client
  .new(token: Settings.slack_admin_token)
  .users_profile_set(
    user: 'USERID', 
    profile: { fields: { { CUSTOM_FIELD_ID =>  { value: 'test' } } } }.to_json
)
```

but API returns me `ok` response with unchanged custom field.

Do I build profile wrong or what else I can do to change custom profile via API?

**Comment by dblock** [comment]
I would first check what the library is sending over the wire [here](https://github.com/slack-ruby/slack-ruby-client/blob/1c9f8c8ef02ba342edb9bb8f0e11ae30a690675e/lib/slack/web/api/endpoints/users_profile.rb#L38), then reproduce this with `curl`, and open an issue with Slack if it's on their side.

**Comment by anton-smagin** [comment]
The problem was about custom field permissions. It was restricted to update it via API. Thank you for your help!
