### ISSUE TITLE
Why is websocket-driver a hard dependency?

### ISSUE THREAD

**Issue by blowfishpro** [slack-ruby/slack-ruby-client#431]
It looks like [it was added to support celluloid](https://github.com/slack-ruby/slack-ruby-client/pull/26/files#diff-6cdc26a667db9927466ffe735f745f90f764211999ce69eb9466d05d434a8938R20), but [it was only loaded by the optional celluloid](https://github.com/slack-ruby/slack-ruby-client/pull/26/files#diff-6dd4211bccc0b5c742e0e0aa2338034534c920a3bb4c9da5a8cacba305859e8eR1) code ([celluloid itself was an optional dependency](https://github.com/slack-ruby/slack-ruby-client/pull/26/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R204-R208)), and [the celluloid code has since been removed](https://github.com/slack-ruby/slack-ruby-client/pull/355).  As far as I can tell it's not loaded anywhere else.

**Comment by dblock** [comment]
You're probably right, Is it not something used by bringing in async-websocket? Please contribute removing it!

**Comment by blowfishpro** [comment]
I still need to set up a Slack workspace and run the integration tests but it looks like the unit tests are passing.

**Comment by dblock** [comment]
We do have a token and run integration tests against Slack here in CI, so don't worry about it too much.

**Comment by ambethia** [comment]
This is a blocker for me right now trying to update some other dependencies in an app.

**Comment by dblock** [comment]
@ambethia Nobody picked this up, please contribute!

**Comment by blowfishpro** [comment]
I have the code it's just not pushed.  I can do that now.
