### ISSUE TITLE
`require': cannot load such file -- slack-ruby-client (LoadError)

### ISSUE THREAD

**Issue by waaleedkhan** [slack-ruby/slack-ruby-client#439]
I have `slack-ruby-client` added in my gem file. But I am getting this error

`[✔] 🚀 
<internal:/opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- slack-ruby-client (LoadError)
	from <internal:/opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/waleedkhan/Developer/now-ios/fastlane/actions/upload_failure_diff_to_slack.rb:2:in `<top (required)>'
	from <internal:/opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/actions/actions_helper.rb:130:in `block in load_external_actions'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/actions/actions_helper.rb:128:in `each'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/actions/actions_helper.rb:128:in `load_external_actions'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane.rb:43:in `load_actions'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:34:in `start'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/bin/fastlane:25:in `<main>'`

**Comment by dblock** [comment]
Did you run `bundle install` and are you running `bundle exec ...`? Post your project for a repro.

**Comment by dblock** [comment]
I suppose this fixed itself.
