### ISSUE TITLE
Automatically create and update running PR with changes from slack-api-ref 

### ISSUE THREAD

**Issue by duffn** [slack-ruby/slack-ruby-client#456]
Every once in awhile there's a PR like this where somebody manually updates the codebase from [`slack-api-ref`](https://github.com/slack-ruby/slack-api-ref/) by running the update Rake task. https://github.com/slack-ruby/slack-ruby-client/pull/455

What about some automated process that runs maybe once per day (sometime after `slack-api-ref`), runs the Rake task, and creates or updates a PR in this repo with the changes generated.

- New changes but no PR -> open a PR with the changes
- New changes with already existing PR -> update the PR with the new changes
- No changes -> do nothing

This wouldn't actually merge anything to the main branch, but just maintain a running PR with changes from `slack-api-ref`. Maintainers of the repo could then merge the PR whenever they like. I'm thinking that this is something like the running PRs from https://github.com/googleapis/release-please

**Comment by dblock** [comment]
Love it. Add an automatic update of CHANGELOG (either simple that says "updated Slack API to [date]" or fancy "added x, y, z method" and those PRs will be mergeable. Also see https://github.com/slack-ruby/slack-ruby-client/issues/10 that was in that spirit.

**Comment by duffn** [comment]
Great. I'll take a go at this.

**Comment by duffn** [comment]
Mmmmm, come on, still not working. Can you close the currently open PR and let's see what happens when it creates a new one since https://github.com/slack-ruby/slack-ruby-client/pull/461?
