### ISSUE TITLE
chat post image

### ISSUE THREAD

**Issue by MarioRuiz** [slack-ruby/slack-ruby-client#463]
Is there any way to send a chat post attached with an image, fex:
![image](https://user-images.githubusercontent.com/459564/229304384-0bc46a5f-fb0b-43a7-8cd7-d648809268d1.png)
If I use send file endpoint then it is sent as a file so it is not displayed
If I use the attachments parameter and include the image URL, it is displayed but then if the URL image is not available anymore then it is not displayed. 
I need this to be able to send images created using the OpenAI generated images and they are just live for one hour

**Comment by duffn** [comment]
>  If I use send file endpoint then it is sent as a file so it is not displayed

What do you mean not displayed? What is your code? The example in the README here works.

```
client.files_upload(
  channels: "#slack-ruby",
  file: Faraday::UploadIO.new("grogu.jpg", "image/jpeg"),
  title: "Grogu",
  filename: "grogu.jpg",
  initial_comment: "I like frogs."
)
```

<img width="569" alt="Screen Shot 2023-04-01 at 12 54 13 PM" src="https://user-images.githubusercontent.com/3457341/229309214-0761ab4c-0826-4952-b0c4-964ead7caa4e.png">

**Comment by MarioRuiz** [comment]
sending this code:
```
client.files_upload(
  channels: "#test-sm",
  file: Faraday::UploadIO.new("./tmp/rmario.jpg", "image/jpeg"),
  title: "Grogu",
  filename: "rmario.jpg",
  initial_comment: "I like frogs."
)
```
I get:
![image](https://user-images.githubusercontent.com/459564/229309790-b2a8a35c-b6e6-4cda-9b2b-7883703a0d06.png)

**Comment by MarioRuiz** [comment]
Ok I think I know why.... It seems like the file I am uploading has .jpg extension but in fact it is a png so Slack is not displaying it
