### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by antoinesaliba** [slack-ruby/slack-ruby-client#91]
Are your examples suppose to work on a windows computer? I have no problem getting them running on a mac but when I try  on windows with the same gems and ruby 2.3.0 it gives me this error every time:

`test.rb:5: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
E, [2016-05-12T17:11:19.461844 #2396] ERROR -- : Actor crashed!
ThreadError: deadlock; recursive locking
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/nio4r-1.2.1/lib/nio/selector.rb:37:in`synchronize'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/nio4r-1.2.1/lib/nio/selector.rb:37:in `deregister'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/nio4r-1.2.1/lib/nio/monitor.rb:52:in`close'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:52:in `wait'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:21:in`wait_readable'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io.rb:54:in `wait_readable'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/udp_socket.rb:28:in`wait_readable'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/udp_socket.rb:44:in `rescue in recvfrom'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/udp_socket.rb:35:in`recvfrom'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/dns_resolver.rb:45:in `resolve'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/tcp_socket.rb:101:in`create_socket'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/tcp_socket.rb:53:in `initialize'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/socket.rb:39:in`new'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/socket.rb:39:in `new'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.7.2/lib/slack/real_time/concurrency/celluloid.rb:80:in`build_socket'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.7.2/lib/slack/real_time/concurrency/celluloid.rb:33:in `run_loop'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.7.2/lib/slack/real_time/concurrency/celluloid.rb:29:in`connect!'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in`dispatch'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in`block in dispatch'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in`block in task'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in`block in create'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:35:in `terminate': task was terminated (Celluloid::TaskTerminated)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:323:in`block in cleanup'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in`cleanup'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:307:in `shutdown'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:299:in`handle_crash'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:171:in `rescue in run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:150:in`run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in`block in initialize'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in`block in instantiate'
        from (celluloid):0:in `remote procedure call'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in`value'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.7.2/lib/slack/real_time/client.rb:51:in`start!'
        from test.rb:41:in `<main>'
`

**Comment by dblock** [comment]
I've never tried this on Windows. I'll rename this issue to Windows support.
